### ISSUE TITLE
Implement bpf_jit_binary_lock_ro()

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#100]
Implement `bpf_jit_binary_lock_ro()` to make sure BPF programs aren't WX.

**Comment by chleroy** [comment]
Implementation of ARCH_HAS_SET_MEMORY proposed by https://patchwork.ozlabs.org/project/linuxppc-dev/cover/20210330045132.722243-1-jniethe5@gmail.com/

**Comment by iamjpn** [comment]
Latest version https://lore.kernel.org/linuxppc-dev/20210510011828.4006623-1-jniethe5@gmail.com/

**Comment by chleroy** [comment]
Merged as https://github.com/linuxppc/linux/commit/62e3d4210ac9c35783d0e8fc306df4239c540a79
