### ISSUE TITLE
Clean up overrides from powerpc Makefiles

### ISSUE THREAD

**Issue by npiggin** [linuxppc/issues#105]
powerpc uses override LD and override CC to get endian and wordsize parameters passed to the compiler/linker. This causes the odd problem because it's not something the kernel build system really expects, and no other arch does it. We should be able to get the right flags passed through the LDFLAGS, CFLAGS, etc variables.

**Comment by npiggin** [comment]
Fixed

1421dc6d48296a9e91702743b31458d337610aa6 ("powerpc/kbuild: Use flags variables rather than overriding LD/CC/AS")

**Comment by mpe** [comment]
Thanks @npiggin :1st_place_medal:
