### ISSUE TITLE
Add BUILD_BUG_ON()'s to ensure we don't break the PT_x #defines vs real pt_regs offsets

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#11]
Some folks aren't aware that `pt_regs` is exposed to userspace and can't be modified. So to be safe we should add build time checks to make sure the ptrace `#defines`, ie. `PT_R0` etc. are correct WRT the `struct pt_regs`.

**Comment by chleroy** [comment]
That's done, insn't it ? linuxppc/linux@002af9391b

**Comment by mpe** [comment]
That's similar but different to what I meant here. I was thinking of the `PT_R0` defines in `uapi/asm/ptrace.h`.

I'll rewrite my patch because I can't find it.

**Comment by mpe** [comment]
Patch sent https://patchwork.ozlabs.org/patch/1186646/

**Comment by chleroy** [comment]
Merged in v5.5 IIUC (https://github.com/linuxppc/linux/commit/b9e0805abf2e92fc275ac5fbd8c1c9a92b00413d)
