### ISSUE TITLE
Audit usage of STACK_FRAME_OVERHEAD vs STACK_FRAME_MIN_SIZE

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#113]
When we merged the ABIv2 support we added a new `#define` for the minimum size of a stack frame, `STACK_FRAME_MIN_SIZE`. This is 32 bytes on ABIv2 and 112 on v1.

In theory `STACK_FRAME_OVERHEAD` should have the same value, however we didn't update `STACK_FRAME_OVERHEAD` because it has ~190 users and many of them actually want more than the minimum size.

So we need to audit all uses of `STACK_FRAME_OVERHEAD` and decide if they can use `STACK_FRAME_MIN_SIZE`, or if they need more space. The end goal being zero uses of `STACK_FRAME_OVERHEAD`.

**Comment by npiggin** [comment]
Patches queued in powerpc next that improve this situation. This could be closed if and when those are merged.

**Comment by npiggin** [comment]
This should be pretty much done for 6.2. There are no more usage of STACK_FRAME_OVERHEAD in arch/powerpc/.

**Comment by mpe** [comment]
Merged as of torvalds/linux@dfecd06bc552, thanks @npiggin :crocodile:
