### ISSUE TITLE
few of the selftest under powerpc directory fails

### ISSUE THREAD

**Issue by abdhaleegit** [linuxppc/issues#114]
Below tests are failing on powerpc machine running upstream kernel

futex_bench
dscr_sysfs_thread_test
cycles_test
instruction_count_test
memcmp
close_clears_pmcc_test
fork_cleanup_test
pmc56_overflow_test

tags: git_version:powerpc-4.15-5-0-g7333b5a

detailed logs are attached here
[selftestlogs.txt](https://github.com/linuxppc/linux/files/1599822/selftestlogs.txt)

**Comment by ruscur** [comment]
Stale enough that we can close this.
