### ISSUE TITLE
Cleanup #ifdef mess in ptrace.c

### ISSUE THREAD

**Issue by mikey** [linuxppc/issues#128]
ptrace.c is a horrible mess of #ifdef of CONFIG_HAVE_HW_BREAKPOINT and CONFIG_PPC_ADV_DEBUG_REGS.

This needs to be cleaned up.

**Comment by chleroy** [comment]
@mikey, have you started doing something ?

Otherwise do you mind if I handle it ? I think I have some idea on how to proceed.

**Comment by chleroy** [comment]
See first try at https://patchwork.ozlabs.org/cover/1121979/

**Comment by mikey** [comment]
> @mikey, have you started doing something ?
> 
> Otherwise do you mind if I handle it ? I think I have some idea on how to proceed.

Sorry for the slow response. No I've not started anything. Thanks for starting this.

**Comment by chleroy** [comment]
Second try, this time is builds properly on all known targets:

https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=116757

**Comment by chleroy** [comment]
@mikey, any feedback on my series ?

@mpe, any thought ?

This is a heavy series and I don't plan to rebase it every second week. Can we agree on a process/schedule to get in merged ?

**Comment by chleroy** [comment]
@mikey @mpe, any feedback ? Did you have a look to my series ?

**Comment by chleroy** [comment]
Version v3 at:

https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=160942

**Comment by chleroy** [comment]
Version v5 at:

https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=161356

Hope it's the good one (crossing fingers)

**Comment by chleroy** [comment]
Series applied in v5.7, first patch https://github.com/linuxppc/linux/commit/da9a1c10e2c7311e923210b6ccd9fbd1ac9132df
