### ISSUE TITLE
Power9 perf raw event encoding is not up to date vs the code

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#145]
The raw event encoding in `arch/powerpc/perf/isa207-common.h` is not up to date for Power9.

At least the SDAR mode (`p9_SDAR_MODE()`) is not documented.

**Comment by maddy-kerneldev** [comment]
This issue can be closed right?

**Comment by mpe** [comment]
Which commit fixed it?

**Comment by maddy-kerneldev** [comment]
Commit 4d3576b20716 ('powerpc/perf: factor out power8 pmu macros and defines') created the isa207-common.h which has raw event encoding common for power8 and power9 DD1.0. But then in commit 458c70173daa ('powerpc/perf: Update raw-event code encoding comment for power8') we moved backed the encoding to power8-pmu.c and added power9 encoding in power9-pmu.c using commit 18201b204286 ('powerpc/perf: power9 raw event format encoding'). In power9-pmu.c we have the SDAR_mode bits updated and called as "sm".
