### ISSUE TITLE
Implement CONFIG_DEBUG_VIRTUAL

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#147]
x86 and arm(64) have `CONFIG_DEBUG_VIRTUAL` which enables extra checking in `virt_to_page()` etc. 
We should implement it to catch bugs before they become a problem.

We have had bugs thereabouts in the past, see e41e53cd4fe3 `powerpc/mm: Fix virt_addr_valid() etc. on 64-bit hash`.

See for inspiration eg: ec6d06efb0ba `arm64: Add support for CONFIG_DEBUG_VIRTUAL`.

**Comment by chleroy** [comment]
Was merged in Linux 5.0

**Comment by mpe** [comment]
See torvalds/linux@6bf752daca07.
