### ISSUE TITLE
Add & use probe_user_read() in show_user_instructions()

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#194]
In commit a932ed3b7181 `powerpc: Don't print kernel instructions in show_user_instructions()` we fixed a bug where we could be tricked into printing kernel text/data based on the userspace NIP.

We could make that safer by adding a `probe_user_read()` rather than using `probe_kernel_read()`.

It would do the `access_ok()` check explicitly using `USER_DS` and then page fault disable etc.

**Comment by chleroy** [comment]
Series at https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=86479

**Comment by mpe** [comment]
Merged as of torvalds/linux@def0bfdbd603, thanks @chleroy :cheese: :clinking_glasses:
