### ISSUE TITLE
Do syscall register clearing

### ISSUE THREAD

**Issue by mikey** [linuxppc/issues#199]
From Kees Cook's blog (https://outflux.net/blog/archives/2018/06/14/security-things-in-linux-v4-17/)

> One of the ways attackers can influence potential speculative execution flaws in the kernel is to leak information into the kernel via “unused” register contents. Most syscalls take only a few arguments, so all the other calling-convention-defined registers can be cleared instead of just left with whatever contents they had in userspace. 

arm64 and x86 are doing this now:

x86: in v4.17
https://git.kernel.org/linus/fa697140f9a2
ARM64 in 4.19
https://git.kernel.org/linus/4378a7d4be30

**Comment by chleroy** [comment]
Such a change could have a performance impact, can it be gated behind some security option ?

**Comment by npiggin** [comment]
This was implemented for 64-bit with commit 993c670a4dfb2.

**Comment by chleroy** [comment]
@npiggin I think the issue is different. In your commit you zeroise volatile regs on return to user.

As far as I understand, the issue is about zeroising the unused registers on syscall entry, for instance if a given syscall uses only r3 r4, then the kernel syscall entry code should zeroize r5 r6 r7 r8

**Comment by npiggin** [comment]
Oh you're right, thanks for the correction.

**Comment by npiggin** [comment]
The problem with doing this -- and it's not just system calls but all interrupts that should be cleared -- is that you still have a good number of "live" arguments in many system calls, so it's really quite trivial to preload them with various kernel or other addresses and call into the system call and try to peturb branch predictor enough and as a matter of course it will just speculate into code that will use those registers as part of address generation. Let alone the kernel being induced to access various addresses via its own kernel-generated GPR values.

So I'm not really sure it's a valid thing to stick a few band-aids over, or if it's just more unquantified security voodoo.

That said, some processors may be able to release physical registers if the architected register is set to 0, and  64s saves all GPRs always now, so it's a pretty trivial thing to do and may have a small performance advantage in some cases.

**Comment by ajdlinux** [comment]
I'm taking a look at this

**Comment by chleroy** [comment]
Series at <https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=302791&state=*>

**Comment by npiggin** [comment]
This is done.

**Comment by rohanmclure** [comment]
https://lore.kernel.org/linuxppc-dev/20221201071019.1953023-1-rmclure@linux.ibm.com/
Configuration options and defaults for register clearing accepted upstream.

**Comment by mpe** [comment]
Merged as torvalds/linux@7cd882df9485988f7d9b3fae04fde4e95a4c7a74

Thanks @rohanmclure :cake:
