### ISSUE TITLE
pkey_amr_mask is badly named

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#207]
Previously `pkey_amr_mask` was a mask, but now it's just the default value. Similarly for the other mask variables.

The meaning changed in commit a57a04c76e06 `powerpc/pkeys: Give all threads control of their key permissions`. But the variable name and comment wasn't updated to match.

**Comment by chleroy** [comment]
Removed in 5.9 by https://github.com/linuxppc/linux/commit/f491fe3f
