### ISSUE TITLE
qemu ppce500 not booting when stack protector is enabled

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#208]
Building a ppc64e config, with `CONFIG_PPC_QEMU_E500=y`, the resulting kernel should boot using:

```
$ qemu-system-ppc64 -nographic -M ppce500 -cpu e5500 -bios $QEMU/pc-bios/u-boot.e500 -m 2G -kernel arch/powerpc/boot/uImage
```

However if stack protector is enabled it doesn't boot, we get no output from u-boot at all.

If drop u-boot (remove the `-bios` setting) then the kernel boots fine?

**Comment by chleroy** [comment]
Just tried with ppc64e_defconfig + CONFIG_PPC_QEMU_E500 on QEMU 2.11.2, compiled with GCC 8.1

[root@po16846vm qemu-2.11.2]# qemu-system-ppc64 -nographic -M ppce500 -cpu e5500 -m 1G -bios /usr/local/share/qemu/u-boot.e500 -kernel /root/linux-powerpc/arch/powerpc/boot/uImage -s


U-Boot 2017.07 (Jul 12 2017 - 12:20:30 +0000)

CPU:   Unknown, Version: 0.0, (0x00000000)
Core:  e5500, Version: 2.0, (0x80240020)
Clock Configuration:
       CPU0:400  MHz, 
       CCB:400  MHz,
       DDR:200  MHz (400 MT/s data rate), LBC: unknown (LCRR[CLKDIV] = 0x00)
L1:    D-cache 32 KiB enabled
       I-cache 32 KiB enabled
DRAM:  1 GiB
L2:    disabled
Using default environment


PCI: base address e0008000
  00:01.0     - 1af4:1000 - Network controller
PCI1: Bus 00 - 00

In:    serial
Out:   serial
Err:   serial
Net:   No ethernet found.
Hit any key to stop autoboot:  0 
WARNING: adjusting available memory to 30000000
## Booting kernel from Legacy Image at 02000000 ...
   Image Name:   Linux-5.1.0-rc1-00601-g4f0721b38
   Image Type:   PowerPC Linux Kernel Image (gzip compressed)
   Data Size:    5573879 Bytes = 5.3 MiB
   Load Address: 00000000
   Entry Point:  00000000
   Verifying Checksum ... OK
## Flattened Device Tree blob at e8000000
   Booting using the fdt blob at 0xe8000000
   Uncompressing Kernel Image ... OK
   Loading Device Tree to 03efc000, end 03ffefff ... OK
MMU: Supported page sizes
         4 KB as direct
      4096 KB as direct
     16384 KB as direct
     65536 KB as direct
    262144 KB as direct
   1048576 KB as direct
MMU: Book3E HW tablewalk not supported
Linux version 5.1.0-rc1-00601-g4f0721b3881e (root@po16846vm.idsi0.si.c-s.fr) (gcc version 8.1.0 (GCC)) #1283 SMP Tue Mar 19 15:16:03 UTC 2019
Using QEMU e500 machine description
printk: bootconsole [udbg0] enabled
CPU maps initialized for 1 thread per core
-----------------------------------------------------
phys_mem_size     = 0x40000000
dcache_bsize      = 0x40
icache_bsize      = 0x40
cpu_features      = 0x00000003008001b4
  possible        = 0x00000003009003b4
  always          = 0x00000003008003b4
cpu_user_features = 0xcc008000 0x08000000
mmu_features      = 0x000a0010
firmware_features = 0x0000000000000000
-----------------------------------------------------
qemu_e500_setup_arch()
barrier-nospec: using isync; sync as speculation barrier
Zone ranges:
  DMA      [mem 0x0000000000000000-0x000000003fffffff]
  Normal   empty
Movable zone start for each node
Early memory node ranges
  node   0: [mem 0x0000000000000000-0x000000003fffffff]
Initmem setup node 0 [mem 0x0000000000000000-0x000000003fffffff]
MMU: Allocated 2112 bytes of context maps for 255 contexts
random: get_random_u64 called from .start_kernel+0xb8/0x6a8 with crng_init=0
percpu: Embedded 22 pages/cpu @(____ptrval____) s50520 r0 d39592 u1048576
Built 1 zonelists, mobility grouping on.  Total pages: 258560
Kernel command line: 
Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes)
Inode-cache hash table entries: 65536 (order: 7, 524288 bytes)
Memory: 952724K/1048576K available (8168K kernel code, 1560K rwdata, 2756K rodata, 508K init, 572K bss, 95852K reserved, 0K cma-reserved)
SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
rcu: Hierarchical RCU implementation.
rcu: 	RCU event tracing is enabled.
rcu: 	RCU restricting CPUs from NR_CPUS=32 to nr_cpu_ids=1.
rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
NR_IRQS: 512, nr_irqs: 512, preallocated irqs: 16
mpic: Setting up MPIC " OpenPIC  " version 1.2 at fe0040000, max 1 CPUs
mpic: ISU size: 256, shift: 8, mask: ff
mpic: Initializing for 256 sources
clocksource: timebase: mask: 0xffffffffffffffff max_cycles: 0x5c4093a7d1, max_idle_ns: 440795210635 ns
clocksource: timebase mult[2800000] shift[24] registered
Console: colour dummy device 80x25
pid_max: default: 32768 minimum: 301
Mount-cache hash table entries: 2048 (order: 2, 16384 bytes)
Mountpoint-cache hash table entries: 2048 (order: 2, 16384 bytes)
*** VALIDATE proc ***
*** VALIDATE cgroup1 ***
*** VALIDATE cgroup2 ***
e500 family performance monitor hardware support registered
rcu: Hierarchical SRCU implementation.
smp: Bringing up secondary CPUs ...
smp: Brought up 1 node, 1 CPU
Using standard scheduler topology
devtmpfs: initialized
clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
futex hash table entries: 256 (order: 2, 16384 bytes)
xor: measuring software checksum speed
   8regs     :  5800.000 MB/sec
   8regs_prefetch:  4045.000 MB/sec
   32regs    :  3029.000 MB/sec
   32regs_prefetch:  4851.000 MB/sec
xor: using function: 8regs (5800.000 MB/sec)
NET: Registered protocol family 16
kworker/u2:0 (29) used greatest stack depth: 12736 bytes left
kworker/u2:0 (30) used greatest stack depth: 12624 bytes left
kworker/u2:0 (22) used greatest stack depth: 11232 bytes left
raid6: int64x8  gen()  1365 MB/s
raid6: int64x8  xor()  1129 MB/s
raid6: int64x4  gen()  1844 MB/s
raid6: int64x4  xor()  1148 MB/s
raid6: int64x2  gen()  1345 MB/s
raid6: int64x2  xor()  1023 MB/s
raid6: int64x1  gen()  1026 MB/s
raid6: int64x1  xor()   613 MB/s
raid6: using algorithm int64x4 gen() 1844 MB/s
raid6: .... xor() 1148 MB/s, rmw enabled
raid6: using intx1 recovery algorithm
SCSI subsystem initialized
usbcore: registered new interface driver usbfs
usbcore: registered new interface driver hub
usbcore: registered new device driver usb
clocksource: Switched to clocksource timebase
kworker/u2:2 (315) used greatest stack depth: 10256 bytes left
NET: Registered protocol family 2
tcp_listen_portaddr_hash hash table entries: 512 (order: 1, 8192 bytes)
TCP established hash table entries: 8192 (order: 4, 65536 bytes)
TCP bind hash table entries: 8192 (order: 5, 131072 bytes)
TCP: Hash tables configured (established 8192 bind 8192)
UDP hash table entries: 512 (order: 2, 16384 bytes)
UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
NET: Registered protocol family 1
RPC: Registered named UNIX socket transport module.
RPC: Registered udp transport module.
RPC: Registered tcp transport module.
RPC: Registered tcp NFSv4.1 backchannel transport module.
workingset: timestamp_bits=62 max_order=18 bucket_order=0
NFS: Registering the id_resolver key type
Key type id_resolver registered
Key type id_legacy registered
JFS: nTxBlock = 7958, nTxLock = 63665
Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
io scheduler mq-deadline registered
io scheduler kyber registered
Serial: 8250/16550 driver, 4 ports, IRQ sharing enabled
printk: console [ttyS0] disabled
serial8250.0: ttyS0 at MMIO 0xfe0004500 (irq = 42, base_baud = 115200) is a 16550A
printk: console [ttyS0] enabled
printk: console [ttyS0] enabled
printk: bootconsole [udbg0] disabled
printk: bootconsole [udbg0] disabled
brd: module loaded
loop: module loaded
st: Version 20160209, fixed bufsize 32768, s/g segs 256
ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
device-mapper: ioctl: 4.40.0-ioctl (2019-01-18) initialised: dm-devel@redhat.com
usbcore: registered new interface driver usbhid
usbhid: USB HID core driver
ipip: IPv4 and MPLS over IPv4 tunneling driver
NET: Registered protocol family 17
Key type dns_resolver registered
drmem: No dynamic reconfiguration memory found
registered taskstats version 1
printk: console [netcon0] enabled
netconsole: network logging started
hctosys: unable to open rtc device (rtc0)
md: Waiting for all devices to be available before autodetect
md: If you don't use raid, use raid=noautodetect
md: Autodetecting RAID arrays.
md: autorun ...
md: ... autorun DONE.

**Comment by chleroy** [comment]
[root@po16846vm linux-powerpc]# grep STACKPROTECTOR .config
CONFIG_HAVE_STACKPROTECTOR=y
CONFIG_CC_HAS_STACKPROTECTOR_NONE=y
CONFIG_STACKPROTECTOR=y
CONFIG_STACKPROTECTOR_STRONG=y

**Comment by mpe** [comment]
Still fails for me with either qemu-3.0.0-3.fc29 or mainline qemu.

**Comment by mpe** [comment]
Turning off STACKPROTECTOR still fixes it.

**Comment by chleroy** [comment]
I'm having the same trouble at the moment with KASAN.
I guess it is due to the size of the kernel ?

**Comment by chleroy** [comment]
If building a lzma uImage instead of a gz uImage, u-boot starts. Unfortunately the uboot shipped with qemu 2.112 doesn't support lzma.

**Comment by chleroy** [comment]
I built latest version of u-boot (2019.04-rc4). 

With it, it works and my KASAN kernel boots fine.

**Comment by chleroy** [comment]
Went a bit too quick. In fact, it is still not working with a too big uImage (about 8Mbytes). But I have activated lzma in the uboot I built, then the same uImage compressed in lzma instead of gzip is about 5.5Mbytes and it works.

**Comment by mpe** [comment]
How did you LZMA compress the uImage?

I tried changing the arguments to `${MKIMAGE}` but it doesn't make my kernel any smaller.

**Comment by chleroy** [comment]
```
#!/bin/sh
powerpc64-linux-objcopy -O binary vmlinux ./vmlinux.bin
rm -f vmlinux.bin.lzma
lzma vmlinux.bin
./scripts/mkuboot.sh -A ppc -O linux -T kernel -C lzma -a 0x0000000000000000 -e 0x0000000000000000 -n Linux -d ./vmlinux.bin.lzma arch/powerpc/boot/uImage

```

**Comment by mpe** [comment]
OK, I want something I can plug into my jenkins setup, so that's not really going to work for me :)

A bit of hacking on the boot Makefile could add support for `uImage.lzma` or something, but I won't have time to do it for a while.

Really we need someone who cares about e500 to maintain this stuff.

**Comment by chleroy** [comment]
Ok, but does it work at least ? Are you able to do it manually and boot with it ?

Yes it would be nice to be able to select uImage compression type, I use lzma on one of my boards which has only 2 Mbytes NOR flash for embedding u-boot and the kernel.

In the meantime, I guess we should also investigate why too big kernels prevent qemu-e500 to start at all. Is it a bug in uboot ? A bug in QEMU ? A parameter somewhere ?

**Comment by mpe** [comment]
It sort of works. I at least get into u-boot, which decompresses the kernel OK.

But then it just gets stuck here:
```
## Flattened Device Tree blob at e8000000
   Booting using the fdt blob at 0xe8000000
   Uncompressing Kernel Image ... OK
   Loading Device Tree to 03efc000, end 03ffefff ... OK
```

Not sure where the bug is. The fact we get zero u-boot output suggests the bug is prior to that, ie. qemu has laid things out wrong?

**Comment by chleroy** [comment]
I have prepared the boot Makefile for supporting lzma uImage.
Have added bzip2 and lzo as well.

https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=99874

**Comment by chleroy** [comment]
Looks like uboot panics in get_linear_ram_size(). Need to findout why.

**Comment by chleroy** [comment]
The fdt is expected at 0xe8000000

When the uImage is big, at address 0xe8000000 there is the content of offset 0x700000 of the uImage file instead of the fdt.

**Comment by chleroy** [comment]
Looks like we enter u-boot with:
- Kernel at 0x2000000 and fdt at 0x2700000

Indeed, the problem is in qemu.

u-boot gets loaded at 0xf00000
fdt gets loaded at 0xf00000 + 0x1800000 = 0x2700000
then kernel gets loaded at 0x2000000, so when it is big it runs over the fdt.

**Comment by chleroy** [comment]
In qemu 2.12.1, the following change fixes the issue, allthough it is a bit gross.

diff --git a/hw/ppc/e500.c b/hw/ppc/e500.c
index 9a85a41362..c4db3d1174 100644
--- a/hw/ppc/e500.c
+++ b/hw/ppc/e500.c
@@ -1009,9 +1009,9 @@ void ppce500_init(MachineState *machine, PPCE500Params *params)
     }
 
     cur_base = loadaddr + payload_size;
-    if (cur_base < (32 * 1024 * 1024)) {
-        /* u-boot occupies memory up to 32MB, so load blobs above */
-        cur_base = (32 * 1024 * 1024);
+    if (cur_base < (48 * 1024 * 1024)) {
+        /* u-boot occupies memory up to 48MB, so load blobs above */
+        cur_base = (48 * 1024 * 1024);
     }
 
     /* Load bare kernel only if no bios/u-boot has been provided */

**Comment by mpe** [comment]
Thanks for debugging it. I'll test that patch here.

**Comment by chleroy** [comment]
@mpe any progress ?

**Comment by mpe** [comment]
Yeah that patch has fixed it for me, I've been carrying that patch in my local qemu tree ever since.

**Comment by chleroy** [comment]
Issue open at QEMU : https://gitlab.com/qemu-project/qemu/-/issues/679

**Comment by chleroy** [comment]
Now that QEMU e500 emulation can start Linux Kernel directly without using Uboot, is that worth keeping this Issue open ?

**Comment by mpe** [comment]
Yeah let's close this. I just use `-kernel` now. Any further work can be tracked on the qemu issue.
