### ISSUE TITLE
Early call to printk on 6xx not 601 leads to illegal instruction exception

### ISSUE THREAD

**Issue by chleroy** [linuxppc/issues#218]
printk() calls sched_clock():

```
notrace unsigned long long sched_clock(void)
{
	if (__USE_RTC())
		return get_rtc();
	return mulhdu(get_tb() - boot_tb, tb_to_ns_scale) << tb_to_ns_shift;
}

```

```
/* Accessor functions for the timebase (RTC on 601) registers. */
/* If one day CONFIG_POWER is added just define __USE_RTC as 1 */
#ifdef CONFIG_6xx
#define __USE_RTC()	(cpu_has_feature(CPU_FTR_USE_RTC))
#else
#define __USE_RTC()	0
#endif

```

When called early, __USE_RTC() returns true on any 6xx leading to calling get_rtc() which is invalid except on 601.

**Comment by mpe** [comment]
@paulusmack is going to see if his 601 even boots still.

**Comment by chleroy** [comment]
Using feature fixup instead of cpu feature would fix it as feature fixups are applied earlier.

Patch at https://patchwork.ozlabs.org/patch/1152995/

**Comment by chleroy** [comment]
Support for powerpc 601 is gone in v5.10, see https://github.com/linuxppc/linux/commit/f0ed73f3fa2cdca65973659689ec9e46d99a5f60
