### ISSUE TITLE
xmon: read only mode

### ISSUE THREAD

**Issue by ajdlinux** [linuxppc/issues#219]
Would be useful to have a mode where xmon operations that can write to memory are restricted. This would allow users using Secure Boot to still enable xmon in a restricted fashion for debugging purposes without violating secure boot integrity guarantees, if their threat model and security requirements deem this compromise acceptable. Also potentially useful just to generally stop people shooting themselves in the foot while xmon-ing.

(suggested in discussion with @mpe and @paulusmack)

**Comment by mpe** [comment]
@cmr-informatik is looking at this one.

**Comment by ajdlinux** [comment]
@cmr-informatik has posted v1 of his patch for this: https://patchwork.ozlabs.org/patch/1069112/

**Comment by cmr-informatik** [comment]
I think this issue can be closed since the patch was accepted.

**Comment by mpe** [comment]
Yep. Merged in torvalds/linux@0acb5f64560a.

Thanks @cmr-informatik :cake:
