### ISSUE TITLE
Can't we drop our version of walk_system_ram_range()

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#221]
We used to have our own version of `walk_system_ram_range()` because the generic version looks at the resource tree, but we didn't populate that with our RAM resources.

But we fixed that in torvalds/linux@c40dd2f76644 `powerpc: Add System RAM to /proc/iomem`.

So we should be able to drop `walk_system_ram_range()` and just use the generic version.
Possibly also `page_is_ram()`.

**Comment by chleroy** [comment]
Patch https://patchwork.ozlabs.org/patch/1034457/

No problem observed on a 6xx (mpc8321) with this patch.

**Comment by mpe** [comment]
Thanks. How did you test it? It's basically only used by memory hotplug AFAICS. `page_is_ram()` gets used a bit more, by eg. `/dev/mem` etc.

**Comment by ajdlinux** [comment]
This appears to break the ehea network driver, according to snowpatch https://openpower.xyz/job/snowpatch/job/snowpatch-linux-sparse/3688//artifact/linux/build_new.log/*view*/

**Comment by mpe** [comment]
Our version is `EXPORT_SYMBOL_GPL`, but the generic version is not exported to modules at all.

**Comment by chleroy** [comment]
> 
> 
> Thanks. How did you test it? It's basically only used by memory hotplug AFAICS. `page_is_ram()` gets used a bit more, by eg. `/dev/mem` etc.

`page_is_ram()` is called by `__ioremap_caller()` and `page_is_ram()` calls `walk_system_ram_range()` . To me this means that if `walk_system_ram_range()` was not working properly we would quickly notice it.

**Comment by mpe** [comment]
Ah true, but only on 32-bit.

**Comment by chleroy** [comment]
Merged in 5.1-rc1 powerpc/linux@26b523356f49a0117c8f9e32ca98aa6d6e496e1a
