### ISSUE TITLE
Per-cpu mapping for kernel patching (patch_instruction()) etc.

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#224]
When STRICT_KERNEL_RWX is enabled we can't directly patch kernel text.

Instead we create a temporary mapping somewhere in the vmalloc area that points to the same physical page as the kernel text we want to patch.

That mapping is inserted into the kernel page tables, so can be used on any CPU, not just the CPU that's doing the patching.

The address of the vmalloced page is per-cpu, but it's not randomised, so it would be feasible for an attacker to write to it from another CPU.

On x86 they are looking at an even better solution which is to make the temporary mapping unique to the CPU that is doing the patching.

The current approach they're trying it to create a temporary mm, switch to that, create the mapping and then switch back to the kernel mm and destroy the temporary mm.

Patches here:
https://lore.kernel.org/lkml/20181205013408.47725-1-namit@vmware.com/

**Comment by cmr-informatik** [comment]
I will take a look at this :+1:

**Comment by chleroy** [comment]
Latest series: https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=253206&state=*

**Comment by chleroy** [comment]
v7 at <https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=271239&state=*>

**Comment by mpe** [comment]
v10 was merged as torvalds/linux@2f228ee1ade5d8d1f26cf94863a36c5693023c58

Thanks @BenjaminGrayNp1  :fortune_cookie:
