### ISSUE TITLE
xmon for secure boot/kernel lockdown

### ISSUE THREAD

**Issue by shenki** [linuxppc/issues#232]
When booting a system with secure boot (or potentially the kernel lockdown series series that most distros carry https://lore.kernel.org/lkml/20190306235913.6631-1-matthewgarrett@google.com/) we should ensure xmon is locked down.

Methods to enable it:

 * sysrq+x (`echo x > /proc/sysrq-trigger`)
 * sysfs (`echo 1 > /sys/kernel/debug/powerpc/xmon`)
 * kernel command line (see https://github.com/linuxppc/issues/issues/189)

Another question is weather a subset of xmon should be usable when in this lockdown mode. There is https://github.com/linuxppc/issues/issues/219 which describes read-only mode. Another subset could be just the ability to view kernel and skiboot logs?

**Comment by ajdlinux** [comment]
@cmr-informatik has sent an RFC for this: https://patchwork.ozlabs.org/patch/1104888/

**Comment by cmr-informatik** [comment]
I have a few things I need to fix (checkpatch poop and a 0-day build fail), but I am holding off on a new patch until the question if we should clear/remove existing breakpoints when transitioning into lockdown=integrity mode is discussed.

**Comment by mpe** [comment]
Implemented in torvalds/linux@69393cb03ccdf29f3b452d3482ef918469d1c098.

Thanks @cmr-informatik :cut_of_meat:
