### ISSUE TITLE
Range check in arch_unmap() looks wrong?

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#241]
tglx points out the check in arch_unmap() looks fishy:

https://lore.kernel.org/lkml/alpine.DEB.2.21.1904191248090.3174@nanos.tec.linutronix.de/

**Comment by chleroy** [comment]
From the mentionned mail from tglx:
```
static inline void arch_unmap(struct mm_struct *mm,
                              unsigned long start, unsigned long end)
{
 	if (start <= mm->context.vdso_base && mm->context.vdso_base < end)
                mm->context.vdso_base = 0;
}

Shouldn't that be: 

 	if (start >= mm->context.vdso_base && mm->context.vdso_base < end)

Hmm?

Thanks,

	tglx
```

I don't think the proposed solution is good either. We need to check whether the removed range overlaps VDSO or not. It can't be done without also knowning vdso_end.

The text should be somethink like
```
 	if (end > vdso_base && start < vdso_end)
```

**Comment by chleroy** [comment]
`arch_unmap()` should go away in the future, see discussion at https://lore.kernel.org/patchwork/patch/1232017/

**Comment by mpe** [comment]
Laurent sent a patch to do that:

https://lore.kernel.org/lkml/9c2b2826-4083-fc9c-5a4d-c101858dd560@linux.vnet.ibm.com/

Because it was a reply patchwork didn't track it, so I missed applying it.

**Comment by chleroy** [comment]
> 
> 
> Laurent sent a patch to do that:
> 
> https://lore.kernel.org/lkml/9c2b2826-4083-fc9c-5a4d-c101858dd560@linux.vnet.ibm.com/
> 
> Because it was a reply patchwork didn't track it, so I missed applying it.

That patch looks too complex. The test is odd, can do simpler I think (see my answer to the patch)
And I don't think it is worth adding a vdso_end pointer in all mm contexts. The VDSO size can be easily re-calculated in arch_unmap()

**Comment by chleroy** [comment]
@ldu4 sent an updated patch at https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20201103171336.98883-1-ldufour@linux.ibm.com/

This patch doesn't apply anymore

In the meantime we have the series from Dmitry: https://lore.kernel.org/lkml/20210611180242.711399-1-dima@arista.com/#r

**Comment by mpe** [comment]
Dmitry says he is planning on doing a v4 of his series, but not sure when, and that we should merge @ldu4's patch in the interim.

**Comment by chleroy** [comment]
arch_unmap() is gone, see commit https://github.com/torvalds/linux/commit/5463bafab476e430a385c6be58249a49b7549629 and https://github.com/torvalds/linux/commit/40b88644dd92d99e572063893c2a247598c238d6
