### ISSUE TITLE
Enable GENERIC_BUG_RELATIVE_POINTERS

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#244]
This saves space in the bug table by storing 32-bit offsets rather than 64-bit pointers.

**Comment by iamjpn** [comment]
I have started this
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20201201005203.15210-1-jniethe5@gmail.com/

**Comment by mpe** [comment]
Merged as linuxppc/linux@1baa1f70ef77.

Thanks @iamjpn :fortune_cookie:
