### ISSUE TITLE
paca->mm_ctx_id is unused

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#249]
Since commit torvalds/linux@48e7b7695745 `powerpc/64s/hash: Convert SLB miss handlers to C`.

This seems straight forward, ie. it should be removed. However there is a comment in `switch_mm_irqs_off()` which mentions `paca->mm_ctx_id`, and it's not clear that we haven't broken the logic it describes.

**Comment by chleroy** [comment]
@npiggin , any opinion ?

**Comment by npiggin** [comment]
I think my comment is actually wrong, I don't think a store can really order that.

What we're worried about I think is the hardware page table walker loading PTEs before that store to mm_cpumask is visible. This could be done easily with ptesync, but that is a much more expensive instruction so we want to have the a regular load that the MMU depends on to set up those PTEs, which we can then order with a hwsync.

I think get_user_context (load of the context ID which is used to then find the VSID hash for the SLB insert in the SLB fault case) is what we need. So the comment should be updated and we can remove mm_ctx_id.

**Comment by npiggin** [comment]
I submitted a patch to update the comment. That removes that reference to mm_ctx_id so I think you can go ahead with removing it now.

**Comment by chleroy** [comment]
@npiggin , I see that there as been a tentative with https://github.com/linuxppc/linux/commit/8fed04d0f6ae then it's been braught back by https://github.com/linuxppc/linux/commit/54be0b9c7 
And then https://github.com/linuxppc/linux/commit/48e7b769 comes.

So, can we re-apply / rebase https://github.com/linuxppc/linux/commit/8fed04d0f6ae ?

**Comment by npiggin** [comment]
That patch at least had an issue that you can't IPI from demote_segment_4k, but I think there may have been deeper concerns about synchronizing updates to these fields vs reading them for fault handling. I didn't entirely get to the bottom of it all.

**Comment by chleroy** [comment]
Ok, then I only remove `mm_ctx_id` and `mm_ctx_slb_addr_limit`

**Comment by chleroy** [comment]
Patch at https://patchwork.ozlabs.org/project/linuxppc-dev/patch/cc8bc507cce433bc9bbfe86f6fc22b29ce21d461.1620060357.git.christophe.leroy@csgroup.eu/

**Comment by npiggin** [comment]
Thanks looks like a good cleanup.

**Comment by mpe** [comment]
Merged as torvalds/linux@13c7dad95176.
