### ISSUE TITLE
Cache helper tweak breaks clang build

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#260]
The commit to tweak the inline asm for the cache helpers broke the clang build.

https://git.kernel.org/powerpc/c/6c5875843b87c3adea2beade9d1b8b3d4523900a

https://lore.kernel.org/linuxppc-dev/20190708191416.GA21442@archlinux-threadripper/

**Comment by chleroy** [comment]
See bug report on clang at https://bugs.llvm.org/show_bug.cgi?id=42762

**Comment by mpe** [comment]
Reverted in torvalds/linux@ed4289e8b488.
