### ISSUE TITLE
pkey selftest changes did not make it upstream

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#267]
The changes to the pkey selftests never got over the line:

http://patchwork.ozlabs.org/project/linuxppc-dev/list/?state=*&series=55981

The first ~5 patches were acked by Dave, but after that he requested some changes.

**Comment by mpe** [comment]
Best approach is probably to try and less invasive series, that just does the bare minimum we need to get the tests working on powerpc.

**Comment by gromero** [comment]
The link above pointing to the patch series doesn't show any patch. I'm wondering if it's because they are already accepted. Should we close it @mpe?

**Comment by ajdlinux** [comment]
Click the X next to "Action Required" in the filters list and you'll see
they were set to Changes Requested

**Comment by mpe** [comment]
Sorry github didn't like the link ending with `*`, I put the state first and now it works.

**Comment by kvaneesh** [comment]
this is now done right?

**Comment by mpe** [comment]
Yes, the v19:

https://lore.kernel.org/all/9b7c54a9b4261894fe0c7e884c70b87214ff8fbb.1585646528.git.sandipan@linux.ibm.com

Was merged as torvalds/linux@f21fda8f6453.

Thanks Sandipan :1st_place_medal:
