### ISSUE TITLE
Remove mmu_pid_bits workaround on later P9s?

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#272]
In `radix_init_pgtable()` we have a workaround where the MMU PID space is segregated between guest and host. Apparently this issue was fixed in later DDs. Was it, if so make the work around conditional on the DD level.

**Comment by iamjpn** [comment]
I think this should be able to be closed as of commit 736bcdd3a9fc ("powerpc/mm: Remove kvm radix prefetch workaround for Power9 DD2.2")

**Comment by mpe** [comment]
Fixed in torvalds/linux@736bcdd3a9fc - thanks @iamjpn :fortune_cookie:
