### ISSUE TITLE
Remove current_is_64bit()

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#275]
Since we enabled `CONFIG_THREAD_INFO_IN_TASK` in commit torvalds/linux@ed1cd6deb013, `current_is_64bit()` in `arch/powerpc/perf/callchain.c` is no longer necessary.

It can be removed and the only usage can be replaced with `is_32bit_task()`.

**Comment by chleroy** [comment]
See https://patchwork.ozlabs.org/patch/1162077/ from Michal

**Comment by chleroy** [comment]
`current_is_64bit()` was removed in Linux v5.5, see https://github.com/linuxppc/linux/commit/42484d2c0f82b666292faf6668c77b49a3a04bc0
