### ISSUE TITLE
Move powerpc VDSO to GENERIC_GETTIMEOFDAY

### ISSUE THREAD

**Issue by chleroy** [linuxppc/issues#276]
Powerpc has two implementations of VDSO gettimeofday, one for PPC32 and one for PPC64. Allthough there are a lot of similarities between the two implementations, the registers used are different and merging both implementations would require some effort.
In addition, VDSO32 lacks COARSE clocks (#41).
And the size of the functions is beyond what is easily maintanable on assembly.

x86 and arm64 have migrated to a generic C implementation of VDSO gettimeofday(), could powerpc also go for it ?

See:
linuxppc/linux@7ac8707479886c75f353bfb6a8273f423cfccb23
linuxppc/linux@28b1a824a4f44da46983cd2c3249f910bd4b797b
linuxppc/linux@00b26474c2f1613d7ab894c525f775c67c8a9e8f

**Comment by mpe** [comment]
Hopefully we can use some of it.

The problem we have is that vdso calls communicate success/fail via `cr0[SO]`, which AFAIK can not be done in C, ie. the entry points have to be in asm.

**Comment by chleroy** [comment]
Latest series at https://patchwork.ozlabs.org/project/linuxppc-dev/patch/e031dc308c6395180554f3f63aa7864f1f92ce46.1601365869.git.christophe.leroy@csgroup.eu/

**Comment by mpe** [comment]
We switched to the generic C VDSO in torvalds/linux@ab037dd87a2f.

Thanks @chleroy.
