### ISSUE TITLE
KUAP makes the signal code do a lot of repeated lock/unlock

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#277]
@antonblanchard reported that KUAP is hurting the signal code, eg. in `restore_sigcontext()`:

```
       │     ↓ bge      cr7,414                                                
       │       isync                                                           
       │       li       r10,-1                                                 
  0.67 │       rldicr   r10,r10,0,1                                            
  7.12 │       mtspr    29,r10                                                 
  1.11 │       isync                                                           
       │414:   std      r8,336(r30)                                            
       │       or       r9,r3,r9                                               
       │       addi     r8,r29,408                                             
       │       nop                                                             
       │       ld       r10,0(r31)                                             
       │       lwa      r10,32(r10)                                            
       │       cmpwi    cr7,r10,0                                              
  0.11 │     ↓ bge      cr7,450                                                
  0.11 │       isync                                                           
  0.33 │       li       r10,0                                                  
  1.22 │       mtspr    29,r10                                                 
  1.11 │       isync                                                           
  0.22 │       ld       r10,0(r31)                                             
```

See also `handle_rt_signal64()`, `setup_sigcontext()`, `sys_rt_sigreturn()` and `__save_altstack()`.

**Comment by mpe** [comment]
One solution is to implement `user_access_begin()/end()`.
Another is to rework the signal code to do bulk copies into/out-of the kernel and do all the small accesses on the in-kernel copy.

Viro is currently (Oct 2019) looking at reworking some of the API.

**Comment by chleroy** [comment]
Implementation of user_access_begin()/end() at https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=155119

**Comment by chleroy** [comment]
@ruscur, did you progress on that ?

I think the user_access_begin()/end() stuff and the associated unsafe_get_user and unsafe_put_user helpers are the way to go, especially with their 'jump to label on error' approach, it really helps making a code readable and performant.

I sent two series recently:
- One to make full use of all adressing modes with __get_user() and __put_user(), see https://patchwork.ozlabs.org/project/linuxppc-dev/patch/c2addbd9d76212242d3d8554a2f7ff849fb08b85.1587040754.git.christophe.leroy@c-s.fr/
- One to take full benefit of the "goto" approach on unsafe_put_user(), see https://patchwork.ozlabs.org/project/linuxppc-dev/patch/97616f62f22f113dd6f1e67771adbce71b830ed3.1587040745.git.christophe.leroy@c-s.fr/

With those, I think we could obtain performant signal handling.

**Comment by chleroy** [comment]
Note that it seems to be the way taken by x86, see arch/x86/kernel/signal.c

**Comment by ruscur** [comment]
Nice.  Do we have any benchmarks that stress the signal code?

**Comment by antonblanchard** [comment]
I noticed it when running https://github.com/antonblanchard/will-it-scale/blob/master/tests/signal1.c

**Comment by chleroy** [comment]
Sent out a series for fixing this copies to user in 32 bits signal code, see https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=196278

signal 32 was mainly using copy_to_user() and __copy_to_user(). Even with that, the performance improvement is significant on book3s/32.

As the 64 bits signal code is making intensive use of put_user() or __put_user(), the performance improvement should be significant if the same changes are done.

**Comment by daxtens** [comment]
cmr is looking at this now. He's reviewing your patch set and rebasing on
top of it.

**Comment by mpe** [comment]
Christophe's series was merged as of torvalds/linux@ef75e73182949a94bde169a774de1b62ae21fbbc.

Chris' series was merged as of torvalds/linux@d3ccc9781560af051554017c702631560bdc0811.

**Comment by mpe** [comment]
A quick profile of `signal1_threads` shows the signal code is at least not right on top of the profile:

```
   7.83%  signal1_threads  [kernel.kallsyms]   [k] system_call_common                                                 ◆
   7.31%  signal1_threads  [kernel.kallsyms]   [k] syscall_exit_prepare                                               ▒
   6.87%  signal1_threads  [kernel.kallsyms]   [k] sys_rt_sigreturn                                                   ▒
   6.05%  signal1_threads  [kernel.kallsyms]   [k] _copy_from_user                                                    ▒
   5.42%  signal1_threads  [kernel.kallsyms]   [k] trace_hardirqs_off                                                 ▒
   5.18%  signal1_threads  [kernel.kallsyms]   [k] trace_hardirqs_on                                                  ▒
   5.17%  signal1_threads  [kernel.kallsyms]   [k] system_call_exception                                              ▒
   4.92%  signal1_threads  [kernel.kallsyms]   [k] arch_local_irq_restore                                             ▒
   3.90%  signal1_threads  [kernel.kallsyms]   [k] exc_virt_0x4c00_system_call                                        ▒
   3.66%  signal1_threads  [kernel.kallsyms]   [k] __unsafe_restore_sigcontext.constprop.0                            ▒
   3.53%  signal1_threads  [kernel.kallsyms]   [k] _raw_spin_lock_irq                                                 ▒
   3.14%  signal1_threads  [kernel.kallsyms]   [k] _copy_to_user                                                      ▒
   2.52%  signal1_threads  [kernel.kallsyms]   [k] recalc_sigpending                                                  ▒
   2.16%  signal1_threads  [kernel.kallsyms]   [k] __sigqueue_alloc                                                   ▒
   2.15%  signal1_threads  [kernel.kallsyms]   [k] __unsafe_setup_sigcontext.constprop.0                              ▒
   1.74%  signal1_threads  [kernel.kallsyms]   [k] handle_rt_signal64                                                 ▒
   1.55%  signal1_threads  libpthread-2.27.so  [.] raise   
```

**Comment by mpe** [comment]
To do significantly better we'd need an unsafe version of `copy_siginfo_to_user()`, which would require generic changes.

Wondering if we should close this and open a new issue for any future work.

**Comment by chleroy** [comment]
Yes we can probably close this one and open a new one.

Unless you have already started looking at it, I'm going to have a look at copy_siginfo_to_user(). Should be easy for native signals, more tricky for compat.
