### ISSUE TITLE
Add missing __init annotations

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#282]
We have a few functions that need `__init` annotations, either because they call other init routines or they are only called by init routines:

* `xive_spapr_disabled()` 
* `get_vec5_feature()`
* `xive_get_max_prio()`
* `xive_irq_bitmap_add()`
* `smp_setup_pacas()`

In `prom-init.c`:
* `add_string`
* `enter_secure_mode`
* `prom_memparse`
* `prom_rtas_hcall`
* `prom_strtoul`
* `__reloc_toc`
* `reloc_toc`
* `setup_secure_guest`
* `tohex`
* `unreloc_toc`

**Comment by mpe** [comment]
Some of these can be found with `CONFIG_DEBUG_SECTION_MISMATCH=y`.

Others won't show up, because in practice they are inlined. But we shouldn't be relying on the inlining, they should still be marked `__init`. You can detect those cases by making the functions non-static temporarily, which should prevent them being inlined and cause the mismatch warning to trigger.

**Comment by chleroy** [comment]
Series at https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=277093&state=*

**Comment by daxtens** [comment]
Merged: d276960d9296b6a9074795fe60a513abf8474e35 through 7da1d1ddd1f02e5de7497a0c849256912652fb6c
