### ISSUE TITLE
Fix/remove no-dwarf2-cfi-asm hack in arch/powerpc/Makefile

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#289]
We have some old cruft/hack in `arch/powerpc/Makefile`:

```
# FIXME: the module load should be taught about the additional relocs
# generated by this.
# revert to pre-gcc-4.4 behaviour of .eh_frame
KBUILD_CFLAGS	+= $(call cc-option,-fno-dwarf2-cfi-asm)
```

Added in 2010 in torvalds/linux@d0679c730395 `kbuild: move -fno-dwarf2-cfi-asm to powerpc only`

**Comment by shenki** [comment]
This was fixed in v5.7, commit c04868df38d8d.

https://lore.kernel.org/linuxppc-dev/9b22a064de6eb1301d92177eb3a38559df7005d3.1583415544.git.naveen.n.rao@linux.vnet.ibm.com/
