### ISSUE TITLE
Move 32 bit system call and interrupt return logic to C

### ISSUE THREAD

**Issue by npiggin** [linuxppc/issues#291]
If/when these are proven out and merged upstream for 64s, it would be good to move other platforms to use the common C code where possible. There is initial C code there for 64e already, just hasn't been well tested and polished.

Christophe had concerns about performance on low end 32 bit devices around GPR saving which might make this difficult, but there might be ways to get around that (e.g., register asm variables can prevent the C function from clobbering non-volatile GPRs, so it's possible that can be used to avoid always saving them.

**Comment by chleroy** [comment]
Test done a few monthes ago:

```
On an 885, null_syscall reports 2227ns (132MHz)
If saving non-volatile regs, it goes to 2419, ie +8.6%

```
```
On an 8321, null_syscall reports 1021ns (333MHz)
If saving non-volatile regs, it goes to 1100, ie +7.7%

```

**Comment by chleroy** [comment]
First tentative at https://patchwork.ozlabs.org/patch/1264805/

On kernel 5.6 this time, null_syscall reports 2149ns (on a 885 at 132 MHz).

Which the patch, we get 2808ns, that is 30% slower.

**Comment by npiggin** [comment]
Thanks Christophe, I have been quite busy trying to fix my bugs for this merge window, I will try to take a look at your stuff (and everything else) as soon as I can after that settles down.

**Comment by chleroy** [comment]
I posted updated series for implementing syscall entry/exit in C , including some additional optimisation. The degradation is now only 8% on an 8xx. I think that is an acceptable impact that is worth it.

https://patchwork.ozlabs.org/project/linuxppc-dev/cover/cover.1611585031.git.christophe.leroy@csgroup.eu/

**Comment by npiggin** [comment]
Great, I have the remainder of your comments suggestions fixed locally I'll post another series, mpe said he would try to take a quick look at things first in case he wanted some other changes. All the common code changes in your patch series look pretty fine to me, I'll go over each patch with a better review though.

Interrupt exit next? :) One day I'll have to try do something about 64e too.

**Comment by chleroy** [comment]
#355 has been created for 64e, this one becomes PPC32 only

**Comment by chleroy** [comment]
System call has been converted, see https://github.com/linuxppc/linux/commit/6f76a01173ccaa363739f913394d4e138d92d718

**Comment by mpe** [comment]
Completed by @chleroy in torvalds/linux@c16728835eec45fa82f4744a52940717ac828f6d
