### ISSUE TITLE
probe_kernel_read() should not require KUAP

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#296]
The KUAP implementation has to use `early_mmu_has_feature()` because it can be called before features are patched. At least one path is via `printk()` that uses `probe_kernel_read()` as described in torvalds/linux@8150a153c013a.

We could fix that if `probe_kernel_read()` didn't try to do any KUAP. And there's zero reason why it *should* be doing KUAP, it's just that `probe_kernel_read()` eventually calls into the user access routines.

`probe_kernel_read()` is weak, so we could override it, or do some more work to make the generic version not use the user access routines - though that would be a cross architecture effort.

**Comment by chleroy** [comment]
See series from Christoph Hellwig, http://git.infradead.org/users/hch/misc.git/shortlog/refs/heads/set_fs-removal

And especially patch http://git.infradead.org/users/hch/misc.git/commit/b13d9208aa3c70d5f3959ad8fde9a846ee0a02ae

**Comment by chleroy** [comment]
Series posted by Christoph Hellwig: https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=195885

**Comment by chleroy** [comment]
`probe_kernel_read()` has become `copy_from_kernel_nofault()`  see https://github.com/linuxppc/linux/commit/fe557319aa06c23cffc9346000f119547e0f289a

**Comment by chleroy** [comment]
With commit https://github.com/torvalds/linux/commit/c33165253492b91337f88c84b11733a4a2d55b60 powerpc implements `__get_kernel_nofault()` .

With that, `copy_from_kernel_nofault()` doesn't do KUAP anymore.

**Comment by chleroy** [comment]
So I think torvalds/linux@8150a15 can be reverted, can't it ?

**Comment by mpe** [comment]
In theory yes, I'll test it.

**Comment by mpe** [comment]
Patch posted:

http://patchwork.ozlabs.org/project/linuxppc-dev/patch/20201217005306.895685-1-mpe@ellerman.id.au/

**Comment by mpe** [comment]
The revert back to `mmu_has_feature()` was merged as torvalds/linux@7613f5a66becfd.
