### ISSUE TITLE
Revisit use of "m<>" constraint once GCC 4.6 is unsupported

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#297]
We have to avoid using the "m<>" asm constraint because GCC 4.6 doesn't support it.

Once the kernel drops support for building with GCC 4.6 we should revisit it, and presumably switch to using "m<>" wherever we can.

See thread at:
https://lore.kernel.org/linuxppc-dev/87sggecv81.fsf@mpe.ellerman.id.au/

**Comment by mpe** [comment]
More conversions here, apply once 4.6 is unsupported:

http://patchwork.ozlabs.org/project/linuxppc-dev/patch/c2addbd9d76212242d3d8554a2f7ff849fb08b85.1587040754.git.christophe.leroy@c-s.fr/

**Comment by shenki** [comment]
Summarising some recent discussion in the thread you linked to, Christophe tried to submit a change to do this but ran into a suspected gcc bug:

> >> Looks like 4.9.4 doesn't accept "m<>" constraint either.
> > 
> > The evidence contradicts this assertion.
> > 
> >> Changing it to "m" make it build.
> > 
> > But that just means something else is wrong.
>  
> > Also, what GCC version *does* work on this?
> 
> Among the versions available in kernel.org crosstool
> 4.7.3 is too old
> 4.8.5 has this error
> 4.9.4 has this error
> 5.5.0 works

The bug went away when some (seemingly unrelated) patches were applied.

**Comment by chleroy** [comment]
The said patches making the bug go away are:

https://github.com/linuxppc/linux/commit/96032f983ca32ad1d43c73da922dbc7022754c3c#diff-dedd8a6ea92a035d609c8caf725dccb6
https://github.com/linuxppc/linux/commit/667e3c413ecf20371692fd2dc37e06dc14d0b140#diff-dfb14cf70a6b902098d387e5191783ec

**Comment by mpe** [comment]
Merged as torvalds/linux@2f279eeb68b8 and torvalds/linux@fcf1f26895a4

**Comment by mpe** [comment]
Unfortunately the `__get_user_asm` change (torvalds/linux@2f279ee) now causes breakage in mainline due to a new usage being added in `lib/iov_iter.c` via torvalds/linux@bfdc59701d6d.

```
/linux/lib/iov_iter.c: In function 'iovec_from_user.part.29':
/linux/arch/powerpc/include/asm/uaccess.h:318:2: error: 'asm' operand has impossible constraints
  __asm__ __volatile__(    \
  ^
/linux/include/linux/compiler.h:78:42: note: in definition of macro 'unlikely'
 # define unlikely(x) __builtin_expect(!!(x), 0)
                                          ^
/linux/arch/powerpc/include/asm/uaccess.h:602:34: note: in expansion of macro 'unsafe_op_wrap'
 #define unsafe_get_user(x, p, e) unsafe_op_wrap(__get_user_allowed(x, p), e)
                                  ^
/linux/arch/powerpc/include/asm/uaccess.h:360:10: note: in expansion of macro '__get_user_asm'
  case 4: __get_user_asm(x, (u32 __user *)ptr, retval, "lwz"); break; \
          ^
/linux/arch/powerpc/include/asm/uaccess.h:394:3: note: in expansion of macro '__get_user_size_allowed'
   __get_user_size_allowed(__gu_val, __gu_addr, __gu_size, __gu_err); \
   ^
/linux/arch/powerpc/include/asm/uaccess.h:100:2: note: in expansion of macro '__get_user_nocheck'
  __get_user_nocheck((x), (ptr), sizeof(*(ptr)), false)
  ^
/linux/arch/powerpc/include/asm/uaccess.h:602:49: note: in expansion of macro '__get_user_allowed'
 #define unsafe_get_user(x, p, e) unsafe_op_wrap(__get_user_allowed(x, p), e)
                                                 ^
/linux/lib/iov_iter.c:1668:3: note: in expansion of macro 'unsafe_get_user'
   unsafe_get_user(len, &uiov[i].iov_len, uaccess_end);
   ^
```

**Comment by chleroy** [comment]
> 
> 
> Unfortunately the `__get_user_asm` change ([torvalds/linux@2f279ee](https://github.com/torvalds/linux/commit/2f279ee)) now causes breakage in mainline due to a new usage being added in `lib/iov_iter.c` via [torvalds/linux@bfdc597](https://github.com/torvalds/linux/commit/bfdc59701d6d).
> 

Which version of GCC ?

**Comment by mpe** [comment]
That's the 4.9.4 from kernel.org

**Comment by mpe** [comment]
This seems to fix it, I haven't checked the generated code:
```
diff --git a/arch/powerpc/include/asm/uaccess.h b/arch/powerpc/include/asm/uaccess.h
index 7c2427f237e1..071339b4d70c 100644
--- a/arch/powerpc/include/asm/uaccess.h
+++ b/arch/powerpc/include/asm/uaccess.h
@@ -325,7 +325,7 @@ extern long __get_user_bad(void);
                ".previous\n"                           \
                EX_TABLE(1b, 3b)                        \
                : "=r" (err), "=r" (x)                  \
-               : "m<>" (*addr), "i" (-EFAULT), "0" (err))
+               : "m" (*addr), "i" (-EFAULT), "0" (err))

 #ifdef __powerpc64__
 #define __get_user_asm2(x, addr, err)                  \
```

**Comment by chleroy** [comment]
Sure removing the "<>" makes it work, but we then loose the benefit of it.

With 5.5.0 from kernel.org it works (and with 8.1, 9.2 and 10.1 as well).

It would be a pitty to loose benefit of that constraint on newer GCC just because GCC 4.9.4 doesn't always handle it correctly.
Should we make it depend on GCC version ?

**Comment by mpe** [comment]
I guess yeah make it depend on the GCC version.

**Comment by chleroy** [comment]
Ok, see series at https://patchwork.ozlabs.org/project/linuxppc-dev/patch/5ffcb064f695d5285bf1faab91bffa3f9245fc26.1603109522.git.christophe.leroy@csgroup.eu/

**Comment by chleroy** [comment]
v3 at https://patchwork.ozlabs.org/project/linuxppc-dev/patch/25e6fca46fda3e2a4298448edbf654f64756eee7.1603358942.git.christophe.leroy@csgroup.eu/

**Comment by mpe** [comment]
I took v2 of patch 1 into fixes for v5.10. I'll plan to merge patches 2 and 3 for v5.11.

**Comment by mpe** [comment]
Merged as linuxppc/linux@592bbe9c505d and linuxppc/linux@d85be8a49e73.

**Comment by chleroy** [comment]
Should https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20100625095606.GG12443@tyan-ft48-01.lab.bos.redhat.com/ be changed to "superseeded" ? Who can do it ?

**Comment by mpe** [comment]
Done.
