### ISSUE TITLE
Feature: secure boot detection on pSeries

### ISSUE THREAD

**Issue by daxtens** [linuxppc/issues#303]
Detect secure-boot status on pseries based on the properties used on pseries.

v1 is at https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1593882535-21368-1-git-send-email-nayna@linux.ibm.com/

This is currently waiting on @naynajain 's  v2.

**Comment by mpe** [comment]
Waiting on v3.

**Comment by mpe** [comment]
v3: https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1594813921-12425-1-git-send-email-nayna@linux.ibm.com/

**Comment by mpe** [comment]
Applied to next.

**Comment by daxtens** [comment]
Thanks @mpe!
