### ISSUE TITLE
Feature: queued spinlocks

### ISSUE THREAD

**Issue by npiggin** [linuxppc/issues#305]
Found to be important on large systems and doesn't hurt small systems. Config option could default to off for 5.9.
Need at least a few numbers, big and small system and uncontended.
Could use more investigation of SPLPAR performance under KVM.

**Comment by mpe** [comment]
v3: https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=187710

**Comment by mpe** [comment]
Waiting on v4.

**Comment by npiggin** [comment]
![throughput](https://user-images.githubusercontent.com/19833002/88385486-c7231900-cdf1-11ea-8cfc-6586693d9eb9.png)
![latency](https://user-images.githubusercontent.com/19833002/88385494-cb4f3680-cdf1-11ea-87aa-d39ede76e317.png)

**Comment by npiggin** [comment]
![throughput](https://user-images.githubusercontent.com/19833002/88391078-c774e180-cdfc-11ea-9ace-0efadeeb8f05.png)
![latency](https://user-images.githubusercontent.com/19833002/88391089-cd6ac280-cdfc-11ea-84df-0bd01f46262b.png)

**Comment by mpe** [comment]
v4: https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=192094

**Comment by mpe** [comment]
Applied to next.
