### ISSUE TITLE
Feature: Add bad memory ranges to nvdimm bad blocks

### ISSUE THREAD

**Issue by santoshs** [linuxppc/issues#309]
http://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=188548

This is a series of two patches:
- The first patch was previously sent by Ganesh separately. https://lore.kernel.org/linuxppc-dev/20200330071219.12284-1-ganeshgr@linux.ibm.com. This makes the dependency clear.

- The second patch was this http://patchwork.ozlabs.org/project/linuxppc-dev/patch/20200416082455.2645740-1-santosh@fossix.org/

All the review comments are addressed.

**Comment by santoshs** [comment]
V2 of the series http://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=188623

**Comment by mpe** [comment]
Applied to next.
