### ISSUE TITLE
Feature: enable kdump support in kexec_file_load syscall

### ISSUE THREAD

**Issue by hbathini** [linuxppc/issues#314]
With secureboot support, kexec_load syscall would be disabled.
Enable support for kdump in kexec_file_load syscall to use it in secureboot environment.

Posted v2: https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=187284

Waiting for review comments.

**Comment by hbathini** [comment]
Posted v3: https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=189406

**Comment by mpe** [comment]
v6: https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=193069&state=*

Applied to next.
