### ISSUE TITLE
Feature: Add coregroup support for powerpc

### ISSUE THREAD

**Issue by srikard** [linuxppc/issues#316]
https://lore.kernel.org/linuxppc-dev/20200714043624.5648-1-srikar@linux.vnet.ibm.com/t/#u

**Comment by mpe** [comment]
Changes requested on v1.

**Comment by srikard** [comment]
@mpe please pick this for v5.9.
 I have unable to add a milestone for this issue.

**Comment by srikard** [comment]
A summary of test results has been posted in response to the cover letter. https://lore.kernel.org/lkml/20200730172240.GE14603@linux.vnet.ibm.com/t/#u 

At this time, there are no pending comments, queries on the v4 version of patchset i.e All the suggestions were accepted/answered and all queries stand answered.

**Comment by mpe** [comment]
I replied with some comments.

Please post a v5 with the comments addressed, and the performance numbers included in the series or cover letter.

**Comment by srikard** [comment]
JFYI, v5 was posted on 10th Aug, addressing all the comments received till now.
Performance numbers and verification details part of the cover letter.
Reference url: https://lore.kernel.org/linuxppc-dev/20200810071834.92514-1-srikar@linux.vnet.ibm.com/t/#u

**Comment by mpe** [comment]
Applied to next.
