### ISSUE TITLE
Reduce the number of search_exception_tables in valid kernel fault path

### ISSUE THREAD

**Issue by npiggin** [linuxppc/issues#317]
copy_to/from_user taking valid page faults should have good performance.

This currently searches exception tables at least once for no pte faults, at least twice for prot faults, and sometimes 3 times. This is easy to consolidate the prot fault case to one.

The search is used as a poor man's KUAP and provides almost no benefit if real KUAP is enabled, it could be avoided completely in that case.

The search after mmap_read_trylock is still necessary as the comment explains.

**Comment by chleroy** [comment]
See series at https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=194507&state=*

Is that what you had in mind ?

**Comment by npiggin** [comment]
Oh nice, yeah that looks pretty good. I will try to review it in time for the next merge window.

**Comment by chleroy** [comment]
New version at https://patchwork.ozlabs.org/project/linuxppc-dev/patch/0d37490a067840f53fc5b118869917c0aec9ab87.1607416578.git.christophe.leroy@csgroup.eu/

This is mainly rebasing on top of Aneesh's changes

I droped the last patch (removal of bad_kuap_fault() warnings) as it doesn't make consensus. We'll see in a second step, maybe we could keep those warnings only when CONFIG_PPC_KUAP_DEBUG is set.

**Comment by npiggin** [comment]
Can this be closed?

**Comment by mpe** [comment]
Yeah I think so, merged as of: torvalds/linux@5f1888a077069988218805534f56b983b6d5710c

I didn't take the removal of the bad_kuap_fault() warnings, that can be a new issue if it needs to be.

**Comment by chleroy** [comment]
> 
> I didn't take the removal of the bad_kuap_fault() warnings, that can be a new issue if it needs to be.

They have been removed, see https://github.com/torvalds/linux/commit/3dc12dfe74300febc568c3b530c0f9bee01f2821

**Comment by mpe** [comment]
OK, what do I know :stuck_out_tongue: 

We still have a WARN in `bad_kernel_fault()`, which I'm happy with.

**Comment by chleroy** [comment]
> 
> We still have a WARN in `bad_kernel_fault()`, which I'm happy with.

Yes that has allowed us to get the search_exception_table() out of the fast path, so everyone is happy :)
