### ISSUE TITLE
Feature: add support for reporting NVDIMM 'life_used_percentage' metric  

### ISSUE THREAD

**Issue by vaibhav92** [linuxppc/issues#318]
Hi Mpe,

Please consider following patch series:
http://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=192378

**Comment by mpe** [comment]
Would really like to see an ack from someone on the nvdimm side.

**Comment by vaibhav92** [comment]
Hi @mpe, 

@kvaneesh has been giving me offline reviews for the patchseries and I have posted a v3 of the series at https://lore.kernel.org/linux-nvdimm/20200730121303.134230-1-vaibhav@linux.ibm.com

**Comment by mpe** [comment]
Would be better if he did it on the list so I can see it happening (I know he did some), and then give you a Reviewed-by / Acked-by tag.

But I really meant Dan or Ira.

I guess I'll pick this up and they can always ask for changes.

**Comment by kvaneesh** [comment]
there is an update required because of some rebasing issue. I will make sure I will review these on the list next time.

**Comment by vaibhav92** [comment]
Posted v4 fixing the rebase issue identified by @kvaneesh at 
https://lore.kernel.org/linux-nvdimm/20200731064153.182203-1-vaibhav@linux.ibm.com/T/#t

**Comment by mpe** [comment]
Applied to next.
