### ISSUE TITLE
Feature : Parse extended CEDE information in pseries-cpuidle driver 

### ISSUE THREAD

**Issue by gautshen** [linuxppc/issues#319]
On pseries Dedicated Linux LPARs, apart from the polling snooze idle state, we currently have the CEDE idle state which cedes the CPU to the hypervisor with latency-hint = 0.

However, the PowerVM hypervisor supports additional extended CEDE states, which can be queried through the "ibm,get-systems-parameter" rtas-call with the `CEDE_LATENCY_TOKEN`. The hypervisor maps these extended CEDE states to appropriate platform idle-states in order to provide energy-savings as well as shifting power to the active units. On existing pseries LPARs today we have extended CEDE with latency-hints {1,2} supported.

In Patches 1-3 of this patchset, we add the code to parse the CEDE latency records provided by the hypervisor. We use this information to determine the wakeup latency of the regular CEDE (which we have been so far hardcoding to 10us while experimentally it is much lesser ~1us), by looking at the wakeup latency provided by the hypervisor for Extended CEDE states. Since the platform currently advertises Extended CEDE 1 to have wakeup latency of 2us, we can be sure that the wakeup
latency of the regular CEDE is no more than this. 

Patch 4 (marked as RFC), expose the extended CEDE states parsed above to the cpuidle framework, provided that they can wakeup on an interrupt. On current platforms only Extended CEDE 1 fits the bill, but this is going to change in future platforms where even Extended CEDE 2 may be responsive to external interrupts.

Patch 5 (marked as RFC), filters out Extended CEDE 1 since it offers no added advantage over the normal CEDE.

Patches v1 posted : https://lore.kernel.org/linuxppc-dev/1594120299-31389-1-git-send-email-ego@linux.vnet.ibm.com/

**Comment by gautshen** [comment]
v2 of the patches posted : https://lore.kernel.org/lkml/1596005254-25753-1-git-send-email-ego@linux.vnet.ibm.com/

Key changes between v1-->v2 : 
* Dropped Patches 4 and 5 which would expose extended idle-states,
   that wakeup on external interrupts, to cpuidle framework.  These
   were RFC patches in v1. Dropped them because currently the only
   extended CEDE state that wakesup on external interrupts is CEDE(1)
   which adds no signifcant value over CEDE(0).
   
 * Rebased the patches onto powerpc/merge.
 
 * No changes in code for Patches 1-3.

**Comment by mpe** [comment]
Waiting on v3 after discussion with ego.

**Comment by gautshen** [comment]
v3 of the patchset posted : https://lore.kernel.org/linuxppc-dev/1596087177-30329-1-git-send-email-ego@linux.vnet.ibm.com/

v2-->v3 key changes:
* Patch 1: Got rid of some `#define`-s which were needed mainly for Patches4 and
   5 of v1, but were retained in v2.

 * Patch 2:

  	* Based on feedback from Michael Ellerman, rewrote the
	  function to parse the extended idle states by explicitly
	  defining the structure of the object that is returned by
	  `ibm,get-system-parameters(CEDE_LATENCY_TOKEN)` rtas-call. In
	  the previous versions we were passing a character array and
	  subsequently parsing the individual elements which can be
	  bug-prone. This also gets rid of the excessive (cast *)ing
	  that was in the previous versions.

	  * Marked some of the functions static and annotated some of
	  the functions with `__init` and data with `__initdata`. This
	  makes Sparse happy.

	  * Added comments for `CEDE_LATENCY_TOKEN`.

	  * Renamed `add_pseries_idle_states()` to
            `parse_xcede_idle_states()`. Again, this is because Patch 4
            and 5 from v1 are no longer there.

 * Patch 3: No functional changes, but minor changes to be consistent
   with Patch 1 and 2 of this series.

**Comment by mpe** [comment]
Applied to next.
