### ISSUE TITLE
Feature: p10 2nd DAWR kvm guest support

### ISSUE THREAD

**Issue by BangoriaRavi** [linuxppc/issues#329]
v1: https://lore.kernel.org/linuxppc-dev/20200723102058.312282-1-ravi.bangoria@linux.ibm.com

This needs to be re-worked as per Paul's review comments

**Comment by mpe** [comment]
What's the status on this?

**Comment by BangoriaRavi** [comment]
Sorry.. was busy with bunch of other priorities. Couldn't make it for 5.10. Targeting it for 5.11 now.

**Comment by BangoriaRavi** [comment]
v2: https://lore.kernel.org/linuxppc-dev/20201124105953.39325-1-ravi.bangoria@linux.ibm.com

**Comment by mpe** [comment]
Expecting this to go via Paul's kvmppc tree.

**Comment by BangoriaRavi** [comment]
v3: https://lore.kernel.org/linuxppc-dev/20201216104219.458713-1-ravi.bangoria@linux.ibm.com

**Comment by mpe** [comment]
Merged via the KVM tree as torvalds/linux@d9a47edabc4f.
