### ISSUE TITLE
Feature: Misc v5.10 small features / cleanups etc.

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#330]
Small things that we want in v5.10 that don't warrant their own tracking issue:

- [ ] Add things here

**Comment by bauermann** [comment]
- [ ] [[v3] powerpc/pseries/svm: Allocate SWIOTLB buffer anywhere in memory](https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20200818221126.391073-1-bauerman@linux.ibm.com/)

**Comment by srikard** [comment]
[v6 Offline memoryless cpuless node 0](https://lore.kernel.org/linuxppc-dev/20200818081104.57888-1-srikar@linux.vnet.ibm.com/t/#u)

**Comment by srikard** [comment]
[v3 powerpc/numa: Restrict possible nodes based on platform ](https://lore.kernel.org/linuxppc-dev/20200817055257.110873-1-srikar@linux.vnet.ibm.com/t/#u)

Reduces the possible nodes on a PowerPc machine based on new associativity property but has a fallback if the new property doesn't exist.

**Comment by srikard** [comment]
[v2 Allow archs to override cpu_smt_mask] (https://lore.kernel.org/linuxppc-dev/20200807074517.27957-1-srikar@linux.vnet.ibm.com/t/#u)

Without this patchset, scheduler on a Fused core PowerVM lpars will use SMT8 threads for wakeup.

**Comment by vaibhav92** [comment]
- [ ] [v2 Limit the readability of 'perf_stats' sysfs attribute](https://lore.kernel.org/linux-nvdimm/20200908212752.GD1930795@iweiny-DESK2.sc.intel.com/T)

Fixes a potential issue with perf_stats attribute that was merged in 5.9

**Comment by npiggin** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20200825075612.224656-1-npiggin@gmail.com/
powerpc/pseries: add new branch prediction security bits for link stack

https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20200825075356.224346-1-npiggin@gmail.com/
powerpc/64s: Add cp_abort after tlbiel to invalidate copy-buffer address

**Comment by vaibhav92** [comment]
- [ ] [ powerpc/papr_scm: Support dynamic enable/disable of performance statistics](https://lore.kernel.org/linux-nvdimm/20200913212115.24958-1-vaibhav@linux.ibm.com/T/#u)

**Comment by vaibhav92** [comment]
- [ ] http://patchwork.ozlabs.org/project/linuxppc-dev/patch/20200913211904.24472-1-vaibhav@linux.ibm.com/
powerpc/papr_scm: Add PAPR command family to pass-through command-set

**Comment by kvaneesh** [comment]
- [ ] http://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=194480 ( u32 -> u64 conversion of lmb_size)

**Comment by chleroy** [comment]
Retire ppc 601, https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=204740
