### ISSUE TITLE
Fix handling of _PAGE_ACCESSED when CONFIG_SWAP is not selected

### ISSUE THREAD

**Issue by chleroy** [linuxppc/issues#335]
The 10 years old commit https://github.com/linuxppc/linux/commit/d069cb4373fe0d451357c4d3769623a7564dfa9f removed the management of _PAGE_ACCESSED in 8xx TLB miss handlers when CONFIG_SWAP is not selected.

According, to Joakim, this is inherited from kernel 2.4

Later, I propagated it to 603 through commit https://github.com/linuxppc/linux/commit/84de6ab0e904d058cc221af564fa44636a6c2c59 and to 40x through commit https://github.com/linuxppc/linux/commit/2c74e2586bb96012ffc05f1c819b05d9cad86d6e

This avoids the minor page fault when _PAGE_ACCESSED is not set.

However pte_young() then returns wrong information because a page may have been accessed but still has _PAGE_ACCESSED unset. And pte_young() seems to be used at several places regardless of the selection of CONFIG_SWAP

No other architecture has done such an optimisation, it is suspicious.

My understanding is that mm might swap out some user text that is hardly used when getting short of memory, even when CONFIG_SWAP is not set, since that text is available in the binary file already. I guess the kernel uses pte_young() to determine whether that text is worth getting swapped out.

**Comment by npiggin** [comment]
You're right it is used for paging out file backed mappings even if swap is not enabled.

**Comment by chleroy** [comment]
Ok, so we have to handle _PAGE_ACCESSED even when CONFIG_SWAP is not set.

Fix for the 603: https://patchwork.ozlabs.org/project/linuxppc-dev/patch/a44367744de54e2315b2f1a8cbbd7f88488072e0.1602342806.git.christophe.leroy@csgroup.eu/

Fix for the 40x: https://patchwork.ozlabs.org/project/linuxppc-dev/patch/b02ca2ed2d3676a096219b48c0f69ec982a75bcf.1602342801.git.christophe.leroy@csgroup.eu/

Fixing series for the 8xx: https://patchwork.ozlabs.org/project/linuxppc-dev/patch/3f2386f94fada00b541be76d6bc4b6409746a72d.1602342819.git.christophe.leroy@csgroup.eu/

**Comment by chleroy** [comment]
For the 8xx, new series at https://patchwork.ozlabs.org/project/linuxppc-dev/patch/af834e8a0f1fa97bfae65664950f0984a70c4750.1602492856.git.christophe.leroy@csgroup.eu/

In v2, the first 3 patches have been squashed, because they are all fixes touching the same part of the code, so to avoid a mess during backport to stable it is easier to have only one patch. The first patch was a one line change on a line that is removed by patch 3, and patch 2 was a two lines patch on the same area of code.
In addition there was a risk that patch 2 applies cleanly on stable while not working.

**Comment by chleroy** [comment]
Some additional inputs to this subject : https://lore.kernel.org/linuxppc-dev/20201020183355.GB397401@cmpxchg.org/T/#md086c47d95de4c2664da49c562deba670246ea91

It confirms that not handling _PAGE_ACCESSED is very bad.

Any change to get the fixes merged into mainline for 5.10 ?

**Comment by mpe** [comment]
Yeah it can definitely go into v5.10.

I don't rush merging patches like that because it's been broken for a long time, and the fix is not super simple, so better to wait another week or two and make sure the fix is right.

**Comment by mpe** [comment]
Fix for 603 merged as torvalds/linux@11522448e641.
Fix for 40x merged as torvalds/linux@0540b0d2ce90.
Fix for 8xx merged as torvalds/linux@33fe43cfd9b1.

Thanks @chleroy :trophy:
