### ISSUE TITLE
Feature: Optimize vcpu_is_preempted for shared lpar case

### ISSUE THREAD

**Issue by srikard** [linuxppc/issues#336]
https://lore.kernel.org/linuxppc-dev/20201028123512.871051-1-srikar@linux.vnet.ibm.com/

Powerpc: Better preemption for shared processor

**Comment by srikard** [comment]
Posted v2 : https://lore.kernel.org/linuxppc-dev/20201202050456.164005-1-srikar@linux.vnet.ibm.com/t/#u

**Comment by mpe** [comment]
Merged as linuxppc/linux@ca3f969dcb11.
