### ISSUE TITLE
Cleanup our VDSO

### ISSUE THREAD

**Issue by chleroy** [linuxppc/issues#337]
This issue is to gather WIP around VDSO with aims at cleaning it up.

We have my series at https://patchwork.ozlabs.org/project/linuxppc-dev/cover/cover.1601197618.git.christophe.leroy@csgroup.eu/
This series mainly cleans up and slims down VDSO setup. Part of it is to move to using the modern _install_special_mapping().

In parallele we have the series from Dmitry at https://lore.kernel.org/patchwork/cover/1334692/ that tries to rework VDSO mapping/unmapping to get more secure unmapping that won't lead to the risk of running in the weed.

Dmitry series misses the changes to powerpc as powerpc VDSO doesn't yet have support of _install_special_mapping()

**Comment by chleroy** [comment]
Dmitry submitted v2: https://lore.kernel.org/patchwork/cover/1344355/

How should we coordinate his series with mine ?

**Comment by mpe** [comment]
A large cross-arch series like that will usually be handled by Andrew Morton. So when your series lands in my next he will rebase Dmitry's series on top of that and either handle the conflicts or kick Dmitry's series back for rework.

**Comment by mpe** [comment]
Christophe's series merged as torvalds/linux@65d2150c8912.

Dmitry's changes are still in flight but should not depend on us, so we won't track those here.
