### ISSUE TITLE
P10 VSX-32 byte instr emulation support + DAWR dd1 workaround

### ISSUE THREAD

**Issue by BangoriaRavi** [linuxppc/issues#338]
P10 VSX-32 byte instr emulation support (v5):
https://lore.kernel.org/linuxppc-dev/20201011050908.72173-1-ravi.bangoria@linux.ibm.com

DAWR dd1 workaround (v3):
https://lore.kernel.org/linuxppc-dev/20201106045650.278987-1-ravi.bangoria@linux.ibm.com

**Comment by mpe** [comment]
Merged as linuxppc/linux@35785b293da0.

And linuxppc/linux@3d2ffcdd2a98.
