### ISSUE TITLE
Implement AT_MINSIGSTKSZ

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#339]
Our `MINSIGSTKSZ` has been wrong (too small) since the addition of VSX to the signal frame.

We can't change the value, it's ABI, and there's no immediate breakage because glibc is covering for us, see: https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=f7c399cff5bd04ee9dc117fb6b0f39597dc047c6;hp=0b2c2ace3601d5d59cf89130b16840e7f132f7a6

But long term it would be good to support the solution the ARM folks came up with, which is using an AUXV entry, namely `AT_MINSIGSTKSZ`. It would also require libc support to be actually useful.

**Comment by chleroy** [comment]
@npiggin posted a series at <https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=289362&state=*>

**Comment by mpe** [comment]
Merged as torvalds/linux@2896b2dff49d

Thanks Nick :banana:
