### ISSUE TITLE
Cleanup remnants of MV64X60 

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#340]
In commit torvalds/linux@92c8c16f345759e87c5d5b771d438ff18ec7593f the last selector of CONFIG_MV64X60 was removed, making CONFIG_MV64X60 always false and therefore anything depending on it dead code.

Clean up any remaining references to it. Note that drivers that depend on `MV64X60 || COMPILE_TEST` should be removed also.

**Comment by mpe** [comment]
EDAC patch posted http://patchwork.ozlabs.org/project/linuxppc-dev/patch/20201207040253.628528-1-mpe@ellerman.id.au/

**Comment by mpe** [comment]
Also reported here: https://bugzilla.kernel.org/show_bug.cgi?id=209277

**Comment by chleroy** [comment]
Last bits:
- https://patchwork.ozlabs.org/project/linuxppc-dev/patch/9c2952bcfaec3b1789909eaa36bbce2afbfab7ab.1616085654.git.christophe.leroy@csgroup.eu/
- https://patchwork.ozlabs.org/project/linuxppc-dev/patch/7fc233cfbda60b87894c3f4a3b0d1e63fdb24b37.1616085654.git.christophe.leroy@csgroup.eu/
- https://patchwork.ozlabs.org/project/linuxppc-dev/patch/19e57d16692dcd1ca67ba880d7273a57fab416aa.1616085654.git.christophe.leroy@csgroup.eu/

**Comment by mpe** [comment]
Final removal of the watchdog driver landed as torvalds/linux@bc65baf73b684.
