### ISSUE TITLE
Feature: Use extended "ibm,thread-groups" for parsing split-l2 information

### ISSUE THREAD

**Issue by srikard** [linuxppc/issues#341]
Gautham posted a patchset to extend ibm,thread-groups parsing that helps Linux to detect the correct L2 topology 
http://lkml.kernel.org/r/1607057327-29822-1-git-send-email-ego@linux.vnet.ibm.com

**Comment by mpe** [comment]
The lkp robot reported a build failure, please fix and repost.

**Comment by gautshen** [comment]
Posted a v2 here: https://lore.kernel.org/linuxppc-dev/1607533700-5546-1-git-send-email-ego@linux.vnet.ibm.com/T/#m043ea15d3832658527fca94765202b9cbefd330d

The lkp robot reported a couple of more build failures with clang and !SMP. Posting a v3 which fixes these errors.

**Comment by gautshen** [comment]
v3 posted : https://lore.kernel.org/lkml/1607596739-32439-1-git-send-email-ego@linux.vnet.ibm.com/T/#m0da763399e89e245c065f02fd0cdcd33f5712

**Comment by mpe** [comment]
Merged as linuxppc/linux@0be47634db0baa9e91c7e635e7e73355d6a5cf43.
