### ISSUE TITLE
Implement Extended BPF on PPC32

### ISSUE THREAD

**Issue by chleroy** [linuxppc/issues#346]
At the time being we only have EBPF for PPC64.

PPC32 has CBPF, and test_bpf module reports only 116 / 366 tests jited, and we also get 7 FAILed tests.

**Comment by chleroy** [comment]
RFC at https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1fed5e11ba08ee28d12f3f57986e5b143a6aa937.1608112797.git.christophe.leroy@csgroup.eu/ hoping that patchwork will soon get the entire series

Alternatively it is found at https://lore.kernel.org/patchwork/patch/1354339/ It is already fully received there.

**Comment by chleroy** [comment]
v2 at https://patchwork.ozlabs.org/project/linuxppc-dev/cover/cover.1616430991.git.christophe.leroy@csgroup.eu/

**Comment by mpe** [comment]
Merged as torvalds/linux@e0ea08c0cacf.
