### ISSUE TITLE
Cleanup oldies in patchwork

### ISSUE THREAD

**Issue by chleroy** [linuxppc/issues#347]
We have a bunch of oldies in patchwork that still have status "new". Lets try to identify them and clean them up.

First one I see is:  https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20100625095606.GG12443@tyan-ft48-01.lab.bos.redhat.com/ ==> Superseeded by https://github.com/linuxppc/linux/commit/ff57698a9610fcf7d9c4469bf68c881eff22e2f8
:heavy_check_mark: 

Second one: https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1430396997-14656-3-git-send-email-haokexin@gmail.com/ ==> Superseeded by v2 https://github.com/linuxppc/linux/commit/4c91bd6eeabb004f283db8a6854b134e2a2de1bc
And the associated patch https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1430396997-14656-2-git-send-email-haokexin@gmail.com/ should go as well
:heavy_check_mark:

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/CAJUS3Xk6jVHWvWugLGD0LNWgw0+XZeP6z+=U4Xa6_GTGNvObBQ@mail.gmail.com/  superseeded by https://github.com/linuxppc/linux/commit/72e349f1124a114435e599479c9b8d14bfd1ebcd

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1444146434-12776-3-git-send-email-danielwa@cisco.com/ and https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1551469472-53043-1-git-send-email-danielwa@cisco.com/
==> Superseeded by https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=98106

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190528120446.48911-2-vincenzo.frascino@arm.com/ ==> superseeded by https://github.com/linuxppc/linux/commit/552263456215ada7ee8700ce022d12b0cffe4802

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190528120446.48911-3-vincenzo.frascino@arm.com/ ==> Not powerpc

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190731154603.41797-7-steven.price@arm.com/ ==> superseeded by https://github.com/linuxppc/linux/commit/070434b13b6ef3d41fa5ebe25d73aa31b359b0c4

**Comment by chleroy** [comment]
Patches from bugzilla daemon cannot be accessed. patchwork bug ?

https://patchwork.ozlabs.org/project/linuxppc-dev/list/?submitter=2339

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20200205005054.k72fuikf6rwrgfe4@google.com/ ==> superseeded by https://github.com/linuxppc/linux/commit/49bf59fd0371b1053a17021f27605f43071584ee

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20200213114342.21712-1-linux@rasmusvillemoes.dk/ ==> merged in https://github.com/linuxppc/linux/commit/4508cf76b1ecdf20a456b6b161acbe78f3b23358

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20200619161327.9564-1-peterx@redhat.com/ ==> merged in https://github.com/linuxppc/linux/commit/428fdc094492e720c342f1c934e7972cbc328d13

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=208121 and https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=212311 have been superseeded by v3

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=212911
https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=213174
https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=213234

One of the three series was merged:
32a0de886eb3 arch, mm: make kernel_page_present() always available
5d6ad668f316 arch, mm: restore dependency of __kernel_map_pages() on DEBUG_PAGEALLOC
2abf962a8d42 PM: hibernate: make direct map manipulations more explicit
77bc7fd607de mm: introduce debug_pagealloc_{map,unmap}_pages() helpers

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=214187 superseeded by https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=216890

**Comment by cmr-informatik** [comment]
> https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=208121 and https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=212311 have been superseeded by v3

I set these to "Superseded" in patchwork.

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20201106015025.1281561-1-santosh@fossix.org/ superseeds https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20201103093235.655665-1-santosh@fossix.org/

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=223064 superseeds https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=221337 and probably also https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20210104221758.981302-1-tyreld@linux.ibm.com/ and https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20210104222422.981457-1-tyreld@linux.ibm.com/

**Comment by chleroy** [comment]
If https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1463471271-26788-2-git-send-email-rashmicy@gmail.com/ and https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1463471271-26788-3-git-send-email-rashmicy@gmail.com/ are still relevant, they need to be reworked to take into account that powerpc/signal is now using uaccess_begin logic.

**Comment by chleroy** [comment]
Patch from Ben https://patchwork.ozlabs.org/project/linuxppc-dev/patch/61ad3646674e6bf541a8f7fb420cdf556d0b2152.camel@kernel.crashing.org/ needs rework, see issue https://github.com/linuxppc/issues/issues/365

**Comment by chleroy** [comment]
An updated version of patch https://patchwork.ozlabs.org/project/linuxppc-dev/patch/fe3a79e078c644d9c1379ef5f8c431d787b6d0c8.camel@kernel.crashing.org/ was merged as https://github.com/linuxppc/linux/commit/40530db7c656

**Comment by chleroy** [comment]
An updated version of https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20180531043417.25073-1-benh@kernel.crashing.org/ was merged as https://github.com/linuxppc/linux/commit/528229d210781b2da66c6d257a326c21099982b5

**Comment by chleroy** [comment]
Something almost same as https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1467966504.2874.27.camel@kernel.crashing.org/ was merged as https://github.com/linuxppc/linux/commit/f0228c413011b7e20de9198c4a7244f498dcda2a

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/87a8eb5dwa.fsf@concordia.ellerman.id.au/ conflicts with https://github.com/linuxppc/linux/commit/7af443ee1697607541c6346c87385adab2214743
And it's not in powerpc arch

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20170801112535.20765-2-bsingharora@gmail.com/
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20170801112535.20765-3-bsingharora@gmail.com/
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20170731121103.6984-4-bsingharora@gmail.com/
Are superseded by Jordan's series

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20170731121103.6984-2-bsingharora@gmail.com/
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20170731121103.6984-3-bsingharora@gmail.com/
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20170731121103.6984-4-bsingharora@gmail.com/

Seems to have been superseded by

https://github.com/linuxppc/linux/commit/970d54f99ceac5bbf27929cb5ebfe18338ba1543
https://github.com/linuxppc/linux/commit/c55d7b5e64265fdca45c85b639013e770bde2d0e

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20180328030932.32169-1-bsingharora@gmail.com/ was superseded by https://github.com/linuxppc/linux/commit/ec5b705c48365549c483fab17d68d15d83bef265

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20170729140901.5887-1-bsingharora@gmail.com/ is superseded by https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=234940&state=*

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190820051106.15744-2-npiggin@gmail.com/ is obsolete, EXCEPTION_COMMON() doesn't exist anymore on 64s

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190902084726.14515-1-msuchanek@suse.de/ needs rework because uaccess has changed quite a lot.

**Comment by chleroy** [comment]
arch_validate_hwbkpt_settings() doesn't exist anymore, following patch needs rework if it is still relevant: https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20171117115230.8794-1-pedromfc@linux.vnet.ibm.com/

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20171208154102.22863-1-ivan@de.ibm.com/ : v2 was merged https://github.com/linuxppc/linux/commit/7813043e1bbcea764c86ef2fcf43aeae2b0e240d

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1513742157-28768-2-git-send-email-maddy@linux.vnet.ibm.com/ something similar merged at https://github.com/linuxppc/linux/commit/acb1feab320e38588fccc568e3767761f494976f

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190610232758.19010-1-radu.rendec@gmail.com/ is not a kernel patch
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190610232758.19010-2-radu.rendec@gmail.com/ needs rebase  if still applicable. If it is, it would be worth an issue here.

**Comment by chleroy** [comment]
A fix of the same issue as https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1515577978-21701-1-git-send-email-shriyak@linux.vnet.ibm.com/ was merged as https://github.com/linuxppc/linux/commit/349524bc0da698ec77f2057cf4a4948eb6349265

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20180328193307.978-1-malat@debian.org/ superseded by https://github.com/linuxppc/linux/commit/c806a6fde1c29e7419afcf94d761827a19c5ffe7

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20180504192313.18625-1-raj.khem@gmail.com/ should be rejected ?

https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20180504192313.18625-2-raj.khem@gmail.com/ is obsoleted by https://github.com/linuxppc/linux/commit/ca6d5149d2ad0a8d2f9c28cbe379802260a0a5e0

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20180530091540.10264-1-colin.king@canonical.com/ merged at https://github.com/linuxppc/linux/commit/e6536a9f94c00a5e1da0a869ccea07e9a59665e4

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20180829092746.30674-1-colin.king@canonical.com/ not for  arch/powerpc/

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20180904174808.GS335@mellanox.com/ not for arch/powerpc/

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20180910074204.10812-1-omosnace@redhat.com/ not for powerpc

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1538031141-138417-1-git-send-email-yuehaibing@huawei.com/ merged as https://github.com/linuxppc/linux/commit/74171e9dab62bd9ab616c1a8f9f1c13af71f4f5d

**Comment by chleroy** [comment]
Series https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=68498&state=* which is marked "under review" requires rebasing if still relevant.

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20181022125550.31170-1-mathias.thore@infinera.com/ merged at https://github.com/linuxppc/linux/commit/ba59d5705825fb9cab3ff092552802f4fefc3635
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20181023114832.31350-1-mathias.thore@infinera.com/ merged at https://github.com/linuxppc/linux/commit/2e7ad56aa54778de863998579fc6b5ff52838571

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20181026172549.3628-1-colin.king@canonical.com/ not powerpc

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20181116121701.14359da0@akathisia/ merged at https://github.com/linuxppc/linux/commit/a225f1567405558fb5410e9b2b90805819df1c67

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1542869385-48337-1-git-send-email-wang.yi59@zte.com.cn/ not powerpc

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20181221042719.29954-1-f.fainelli@gmail.com/ not powerpc

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190128233309.14447-1-chrisadr@gentoo.org/ merged at https://github.com/linuxppc/linux/commit/08434ab4694887effbdcae518f29062274871c8d

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190206063024.8489-1-rashmica.g@gmail.com/ superseded by https://patchwork.ozlabs.org/project/linuxppc-dev/patch/50ad16925a66ac53890286ceafbf84f6fc324baa.1614600516.git.christophe.leroy@csgroup.eu/

**Comment by chleroy** [comment]
Series https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=94209&state=* not powerpc

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190227221159.78055-1-cai@lca.pw/ merged at https://github.com/linuxppc/linux/commit/c38ca265525a00d635219450e8fcc858082ff630

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190312202008.29681-1-malat@debian.org/ superseded by https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190312212318.17822-1-malat@debian.org/ which itself should be superseded by the proposal from @mpe in the associated discussion which is Reviewed-by Mathieu

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190316214016.6612-1-colin.king@canonical.com/ not powerpc

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190317220516.92654-1-cai@lca.pw/ merged at https://github.com/linuxppc/linux/commit/bff25143da0d623a1765bf78dbc82044e46da5a4

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190322143008.21313-2-longman@redhat.com/ merged at https://github.com/linuxppc/linux/commit/46ad0840b1584b92b5ff2cc3ed0b011dd6b8e0f1
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190322143008.21313-3-longman@redhat.com/ merged at https://github.com/linuxppc/linux/commit/390a0c62c23cb026cd4664a66f6f45fed3a215f6
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190322143008.21313-4-longman@redhat.com/ merged at https://github.com/linuxppc/linux/commit/ddb20d1d3aed8f130519c0a29cd5392efcc067b8

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=101851&state=* is an architecture wide series that was never merged it seems.

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1556893635-18549-6-git-send-email-ynezz@true.cz/ not powerpc
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1556893635-18549-11-git-send-email-ynezz@true.cz/ merged at https://github.com/linuxppc/linux/commit/ea168cdf129944a11471dff5af93fc3c81c22c35

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190515121008.3992-1-malat@debian.org/ superseded by https://github.com/linuxppc/linux/commit/d25da505c3f567a8667adb0118de1400468172ac

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190515135146.5866-1-malat@debian.org/ something similar merged at https://github.com/linuxppc/linux/commit/548c54acba5bd1388d50727a9a126a42d0cd4ad0

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190523064956.29008-1-malat@debian.org/ obsoleted by https://github.com/linuxppc/linux/commit/45ff3c55958542c3b76075d59741297b8cb31cbb

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1562317084-13140-1-git-send-email-wen.yang99@zte.com.cn/ changes required it seems

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1562317260-13492-1-git-send-email-wen.yang99@zte.com.cn/ obsoleted by https://github.com/linuxppc/linux/commit/c1e53367dab15e41814cff4e37df8ec4ac8fb9d7

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190718193112.17709-1-gomonovych@gmail.com/ not powerpc

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/8fab346b73991afcc6bc602253c973e5d4ecde95.1563862014.git.viresh.kumar@linaro.org/ not arch/powerpc/

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190723080851.7648-1-nishkadg.linux@gmail.com/ merged at https://github.com/linuxppc/linux/commit/3bd4952853d69659e58d1d4a4964383cb536b5be

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190731130037.GN9330@dhcp22.suse.cz/ not a plain patch and not for powerpc

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1565297931-21138-1-git-send-email-youri.querry_1@nxp.com/ not powerpc

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/238d3e33-5222-3829-742a-ced4e71a56cd@web.de/ merged at https://github.com/linuxppc/linux/commit/32e594f9a63f6bc7fdd396d9bc0a77b18208332b

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1567710063-922-1-git-send-email-youri.querry_1@nxp.com/ not powerpc

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1568001906-5750-1-git-send-email-kernelfans@gmail.com/ merged at https://github.com/linuxppc/linux/commit/be5470e0c285a68dc3afdea965032f5ddc8269d7

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/eb3d8f42231aec65b64b079dd17bd6c008a3fe29.1568127106.git.christophe.leroy@c-s.fr/ not powerpc

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1568724534-146242-1-git-send-email-linyunsheng@huawei.com/ not powerpc

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190917143753.GA12300@redhat.com/ superseded by https://github.com/linuxppc/linux/commit/324a69467f12652b21b17f9644faa967d3d8bbdf

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190920062544.180997-16-wangkefeng.wang@huawei.com/ merged at https://github.com/linuxppc/linux/commit/2ee9a0db924e

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190920084540.3449-1-lei.xu@nxp.com/ merged as https://github.com/linuxppc/linux/commit/7db57e77586744af46c8bbf8f831bb2b941b7afc

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190920161826.GA6894@nishad/ merged as https://github.com/linuxppc/linux/commit/7ed42113ce03

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190923181420.31743-1-harish@linux.ibm.com/ merged as https://github.com/linuxppc/linux/commit/0695f8bca93ea0c57f0e8e21b4b4db70183b3d1c

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20191014183108.24804-2-nsaenzjulienne@suse.de/ merged as https://github.com/linuxppc/linux/commit/8b5369ea580964dbc982781bfb9fb93459fc5e8d

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=135087&state=* superseded by v2 https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=136572&state=*

**Comment by chleroy** [comment]
Discussion around https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20191023013635.2512-1-oohall@gmail.com/ suggests to request changes to the patch ?

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20191025122851.30182-3-christian.brauner@ubuntu.com/ merged as https://github.com/linuxppc/linux/commit/9b4feb630e8e9801603f3cab3a36369e3c1cf88d

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20191029034027.GA7226@saurav/ merged as https://github.com/linuxppc/linux/commit/9214cf0f48ca

**Comment by chleroy** [comment]
Series https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=139764&state=* superseded by https://github.com/linuxppc/linux/commit/894fa235eb4c ?

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20191113161340.27228-1-nsaenzjulienne@suse.de/ merged as https://github.com/linuxppc/linux/commit/a7ba70f1787f977f970cd116076c6fce4b9e01cc

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20191117012858.47t7zd3pbdlqz2mv@yavin.dot.cyphar.com/ not powerpc merged by Al Viro

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1574144860-22954-1-git-send-email-zhengbin13@huawei.com/ merged as https://github.com/linuxppc/linux/commit/4de0a8355463

**Comment by chleroy** [comment]
Series https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=144099&state=* and https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=144110&state=* not powerpc and already merged

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/5dd59403.1c69fb81.f6a76.2143@mx.google.com/ is not a patch

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20191122182144.20633-1-minyard@acm.org/ needs rebase if still relevant

**Comment by chleroy** [comment]
Yousef work https://patchwork.ozlabs.org/project/linuxppc-dev/list/?submitter=74581 was merged as https://github.com/linuxppc/linux/commit/4d37cc2dc3df

**Comment by chleroy** [comment]
Series https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=148136&state=* is not powerpc

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20191213000657.931618-6-dima@arista.com/ merged as https://github.com/linuxppc/linux/commit/d68fefdd5b5f107403568c8a4650e858132bd83a
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20191213000657.931618-32-dima@arista.com/ merged as https://github.com/linuxppc/linux/commit/f5e95c4fe42ff39850a459e620f0d91dd7cf2df0
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20191213000657.931618-50-dima@arista.com/ merged as https://github.com/linuxppc/linux/commit/06129311c68c

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20210326191720.138155-1-dima@arista.com/ merged as https://github.com/linuxppc/linux/commit/1c4bce675385

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20191213072036.11170-1-harish@linux.ibm.com/ obsoleted by https://github.com/linuxppc/linux/commit/24c3f063c57b2a8ae21b259bcfa7690e2eb56dd9

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20191218020842.186446-1-chenzhou10@huawei.com/ superseded by https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20191219111812.180386-1-chenzhou10@huawei.com/

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20191219215146.27278-1-sukadev@linux.ibm.com/ merged as https://github.com/linuxppc/linux/commit/ce477a7a1cdfc9aaafcfd03b45bde131a88d51de
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20191219215146.27278-2-sukadev@linux.ibm.com/ merged as https://github.com/linuxppc/linux/commit/3a43970d55e9fd5475d3c4e5fe398ab831ec6c3a

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20191220001000.39859-1-colin.king@canonical.com/ merged as https://github.com/linuxppc/linux/commit/5ed94dcdb88b

**Comment by chleroy** [comment]
============== ARRIVED AT JANUARY 2020 ===============

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20200107174748.9616-6-wsa+renesas@sang-engineering.com/ merged as https://github.com/linuxppc/linux/commit/f12c529005dc

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20200116102758.GC25138@fm.suse.cz/ merged as https://github.com/linuxppc/linux/commit/a83836dbc53e96f13fec248ecc201d18e1e3111d

**Comment by chleroy** [comment]
Series https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=154579&state=* obsoleted by https://github.com/linuxppc/linux/commit/344fbab991a568dc33ad90711b489d870e18d26d

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1580123761-19536-1-git-send-email-andrei.botila@nxp.com/ not powerpc

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20200128221113.17158-1-cheloha@linux.ibm.com/ superseded by https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20200221172901.1596249-2-cheloha@linux.ibm.com/ and https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20200221172901.1596249-3-cheloha@linux.ibm.com/ ?

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20200311230815.1432367-1-cheloha@linux.ibm.com/ merged as https://github.com/linuxppc/linux/commit/e5e179aa3a39c818db8fbc2dce8d2cd24adaf657

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20200910175637.2865160-1-cheloha@linux.ibm.com/ merged as https://github.com/linuxppc/linux/commit/72cdd117c449896c707fc6cfe5b90978160697d0

**Comment by chleroy** [comment]
Series https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=156536&state=* still marked "under review".
First patch merged as https://github.com/linuxppc/linux/commit/2464cc4c345699adea52c7aef75707207cb8a2f6 . Not checked patch 2 and 3.

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/426f75e09ac1a6879a6d51f592bf683c698b4bda.1580959044.git.sbobroff@linux.ibm.com/ not powerpc

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/4d32ab4e1fb2edb691d2e1687e8fb303c09fd023.1581504803.git.michal.simek@xilinx.com/ merged as https://github.com/linuxppc/linux/commit/06e85c7e9a1c1356038936566fc23f7c0d363b96

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/7f63e8a8-95c5-eeca-dc79-3c13f4d98d39@lwfinger.net/ is not a patch.

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20200213151532.12559-1-gromero@linux.ibm.com/ superseded by https://github.com/linuxppc/linux/commit/1dff3064c764b5a51c367b949b341d2e38972bec

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20200302201436.17030-1-krzk@kernel.org/ not powerpc

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20200304004746.4557-1-afzal.mohd.ma@gmail.com/ merged as https://github.com/linuxppc/linux/commit/b4f00d5b2098

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1583289211-5420-1-git-send-email-nayna@linux.ibm.com/ merged as https://github.com/linuxppc/linux/commit/9e2b4be377f0d715d9d910507890f9620cc22a9d

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1519055107-17941-1-git-send-email-sudeep.holla@arm.com/ and https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1519647376-3352-1-git-send-email-sudeep.holla@arm.com/ are rebased as https://patchwork.ozlabs.org/project/linuxppc-dev/patch/1fff2054e5dfc00329804dbd3f2a91667c9a8aff.1623438544.git.christophe.leroy@csgroup.eu/

**Comment by chleroy** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/37a5342c67e1b68b9ad06aca8da245b0ff409692.1583896348.git.joe@perches.com/ merged as https://github.com/linuxppc/linux/commit/8fc6ba0a

**Comment by chleroy** [comment]
Cleanup work being now done directly in patchwork, creating new dedicated issues here when a patch or series deserves more focus.
