### ISSUE TITLE
What is the future of 40x family ?

### ISSUE THREAD

**Issue by chleroy** [linuxppc/issues#349]
40x is an old powerpc32 family which seems to be dormant.

We have very little ways to maintain it, 405 platform support in QEMU seems uncomplete (missing BIOS) so at the time being it seems we have no way to tests changes done on 40x branches.

Some general work on powerpc32 have impact on the 40x, what approach do we want to take:
- Make changes that impact 40x which testing them, and wait until someone cries
- Create a parking branch for 40x than we leave unchanged
- Remove 40x family from the mainline

**Comment by chleroy** [comment]
An article on the subject on Phoronix: https://www.phoronix.com/scan.php?page=news_item&px=PowerPC-40x-400-Linux-Removal

**Comment by chleroy** [comment]
Feedback from @mpe :

On the one hand we want to remove as many legacy platforms as possible,
to ease maintenance of the code for the platforms that are still in
active use.

But on the other hand we have some kind of duty to maintain code that
works, even for old platforms, as long as it doesn't impose "too much"
maintenance burden.

We also have very little idea of who is using old platforms, and whether
anyone really minds if we drop something like 40x. At least until we
drop it, and then we might eventually hear from someone, but it's often
too late by then.

Ben did say he thought we should keep 40x, but I'm not sure why. It's
true that IBM servers have a 405 in them to do power management etc.,
but they don't run Linux, and I don't think there's any chance they ever
would.

There was a discussion at Plumbers last year about having a more formal
process where we track who is using a platform/CPU/other-feature, and
what for, and have better visibility around when things are likely to be
removed. But of course not much has come from that, other than Arnd's
mail proposing things that can be removed.

**Comment by chleroy** [comment]
Some work was done recently on QEMU to revive ppc40x support. With QEMU mainline plus patch https://www.mail-archive.com/qemu-devel@nongnu.org/msg861928.html a 40x kernel can be booted on QEMU.

See guidance at https://github.com/legoater/qemu/wiki/ref405ep

**Comment by mpe** [comment]
It's over a year since the Phronix article, and AFAIK no one has appeared to advocate for 40x staying supported. So my impression is there's basically no users anymore. The [qemu discussion](https://lore.kernel.org/qemu-devel/18fa56ee-956e-ee2f-9270-82aa96dfde09@redhat.com/) thread seems to indicate likewise.

It's good that Cedric has gotten it semi-working on the qemu side, so we can at least be somewhat sure that what we have in Linux still works.

I don't have a good handle on how much code we'd be able to remove if we dropped all 40x support, some of it is tangled up with 44x support, that would be good to know, so we can weigh the cost of keeping it vs the benefit of dropping it.

**Comment by chleroy** [comment]
Series https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=219513&state=* provides some indications:

Patch 1: 13 files changed, 593 deletions(-)
Patch 2: 13 files changed, 1 insertion(+), 2037 deletions(-)
Patch 3: 35 files changed, 29 insertions(+), 1787 deletions(-)

**Comment by legoater** [comment]
Here is a buildroot patch which automates the build of a rootfs 405 image, a Linux 5.17.7 image and QEMU 7.0.0 for tests : https://github.com/legoater/buildroot/commit/b2b73249a646f823b859b5c7a3e51ead8b97de04

Simply run :

**Comment by legoater** [comment]
Here is a branch : https://github.com/legoater/qemu/commits/ppc-ref405ep adding PCI which tests a little more the QEMU models and the Linux kernel.

**Comment by mpe** [comment]
For reference, OpenWrt dropped ppc40x support in 2019:
https://openwrt.org/docs/techref/targets/ppc40x
https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=406a3826dcbb48b5ea42f2d9e96ff92721a6440a

**Comment by legoater** [comment]
QEMU 7.2 will drop support for the taihu machine : 
https://qemu-project.gitlab.io/qemu/about/deprecated.html#ppc-405-taihu-machine-since-7-0

**Comment by mpe** [comment]
Doesn't seem like any actual 40x users have appeared (that I've seen). It's nice that the qemu support has been tidied up, but it's silly for the kernel/qemu to keep maintaining support for each other when there are no actual users.

I'll rebase Christophe's series and repost it?

**Comment by chleroy** [comment]
Yes @mpe if you can do that it will help with maintenance and ease adding new functionnalities.

**Comment by mpe** [comment]
New removal series: https://lore.kernel.org/linuxppc-dev/20240506125152.78174-1-mpe@ellerman.id.au/T/#m95f350b4ec06d32123c7594f8b0f9e8d2aa73549

**Comment by mpe** [comment]
Final [series](https://lore.kernel.org/all/172030740410.964765.17392972496862858325.b4-ty@ellerman.id.au/) was applied as torvalds/linux@d5d1a1a55a7f227c0f41847b0598982f0a93170d.
