### ISSUE TITLE
Rework kexec_fdt_totalsize_ppc64() after v5.12 merge

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#351]
There was a minor conflict between the addition of kexec_fdt_totalsize_ppc64() and some refactoring in the devicetree tree.

Once both trees are merged we need to rework kexec_fdt_totalsize_ppc64() slightly, as it will be over allocating.

More details: https://lore.kernel.org/lkml/CAL_JsqJ9Ske4hkWn3uo8-nef29MQ1DkNdtE=gxbqj8CKrtQorg@mail.gmail.com/

**Comment by hbathini** [comment]
Thiago posted a patch to fix this:
  https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20210220005204.1417200-1-bauerman@linux.ibm.com/

**Comment by mpe** [comment]
The conflicting series was withdrawn from v5.12, so this should now be fixed up as part of that series.

**Comment by hbathini** [comment]
With the patch picked by Rob, this issue can be considered closed:

  https://lists.ozlabs.org/pipermail/linuxppc-dev/2021-March/225502.html
  ("[PATCH v2] powerpc/kexec_file: Restore FDT size estimation for kdump kernel")
