### ISSUE TITLE
Wire up KFENCE on powerpc

### ISSUE THREAD

**Issue by chleroy** [linuxppc/issues#353]
Kernel 5.12 brings KFENCE, a lighter alternative to KASAN.

Seems easy to wire up, see https://github.com/torvalds/linux/commit/840b239863449f27bf7522deb81e6746fbfbfeaf

I'll give it a try

**Comment by mpe** [comment]
32-bit done by @chleroy in torvalds/linux@90cbac0e995d.

64-bit in progress from @iamjpn:
  http://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=244099

**Comment by mpe** [comment]
There were problems with the 64-bit support:
  https://lore.kernel.org/linuxppc-dev/877dim2s5t.fsf@mpe.ellerman.id.au/

**Comment by mpe** [comment]
The 64-bit version might be OK now since: linuxppc/linux@a4c182ecf335

**Comment by ruscur** [comment]
@NMiehlbradt is looking at reviving Jordan's series, which should hopefully Just Work™ now.

**Comment by mpe** [comment]
Merged as torvalds/linux@a5edf9815dd739fce660b4c8658f61b7d2517042
