### ISSUE TITLE
Enable ARCH_HAS_DEBUG_VM_PGTABLE

### ISSUE THREAD

**Issue by npiggin** [linuxppc/issues#357]
675bceb097e6fb9769309093ec6f3d33a2fed9cc ("powerpc/mm: Remove DEBUG_VM_PGTABLE support on powerpc") removed this from powerpc.

Investigate if it is still broken and fix it if so, then enable this option for powerpc.

**Comment by kvaneesh** [comment]
https://lore.kernel.org/linuxppc-dev/20210318034855.74513-1-aneesh.kumar@linux.ibm.com

**Comment by mpe** [comment]
Still causes breakage https://bugzilla.kernel.org/show_bug.cgi?id=213069

**Comment by mpe** [comment]
Re-enabled in torvalds/linux@937c49d10b4d.
