### ISSUE TITLE
Add support for GENERIC_VDSO_TIME_NS / TIME_NS (time namespaces)

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#359]
There's some arch specific work needed in the vdso to support `GENERIC_VDSO_TIME_NS`, which then allows `TIME_NS` to be enabled.

See eg torvalds/linux@eeab78b05d202f15e58ab10675a4f736a1c9bd29

**Comment by chleroy** [comment]
See series v1 at https://patchwork.ozlabs.org/project/linuxppc-dev/cover/cover.1617202094.git.christophe.leroy@csgroup.eu/

**Comment by mpe** [comment]
Implemented by @chleroy in torvalds/linux@74205b3fc2ef
