### ISSUE TITLE
cacheinfo: Fix L3 shared_cpu_map/list  reporting for P10

### ISSUE THREAD

**Issue by gautshen** [linuxppc/issues#371]
On POWER10 big-core system, the `sysfs shared_cpu_list/map` file for the L3 cache reports all the CPUs in the big-core.
```
grep . /sys/devices/system/cpu/cpu0/cache/index*/shared_cpu_list
/sys/devices/system/cpu/cpu0/cache/index0/shared_cpu_list:0,2,4,6
/sys/devices/system/cpu/cpu0/cache/index1/shared_cpu_list:0,2,4,6
/sys/devices/system/cpu/cpu0/cache/index2/shared_cpu_list:0,2,4,6
/sys/devices/system/cpu/cpu0/cache/index3/shared_cpu_list:0-7
```

This is incorrect as only the CPUs in the constituent small core share the L3 cache. 

The device-tree property `"ibm,thread-groups"` with the value  `2` indicates that the CPUs
share both the L2 and L3 caches. Use this to correctly discover the L3 cache scope on P10 systems and report the correct siblings that share L3 via the sysfs.

v2 : https://lore.kernel.org/linuxppc-dev/20210728175607.591679-1-parth@linux.ibm.com/
v1 : https://lore.kernel.org/linuxppc-dev/20210615070804.390341-1-parth@linux.ibm.com/

**Comment by mpe** [comment]
v2 merged as torvalds/linux@e9ef81e1079b0c4c374fba0f9affa7129c7c913b.

Thanks @gautshen :100:
