### ISSUE TITLE
cpufreq:powernv: Fix init_chip_info initialization in numa=off

### ISSUE THREAD

**Issue by pratiksampat** [linuxppc/issues#373]
When numa=off kernel command-line is used, `cpumask_of_node(chip[i])` for all the chips after from the first will result in NULL and copying NULL may yield undefined behavior. To mitigate this, instead of using `cpumask_of_node` maintain a chip cpumask derived from all the cpus that we iterated on in the the last loop using `cpu_to_chip_id(cpu)`.

The crash was first noticed with a kernel configuration with the debug parameters enabled.

v2: https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20210728120500.87549-2-psampat@linux.ibm.com/
v1: https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20210726170758.61041-1-psampat@linux.ibm.com/

**Comment by mpe** [comment]
Merged v2 as torvalds/linux@f34ee9cb2c5a.

Thanks @pratiksampat :fortune_cookie:
