### ISSUE TITLE
Cleanly separate CFLAGS and AFLAGS in a/p/boot/Makefile

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#378]
The changes to drop GCC 4.9 support inadvertently broke the powerpc build, which turned out to be due to `arch/powerpc/boot/Makefile` being sloppy about keeping CFLAGS and AFLAGS separate.

See the discussion [here](https://lore.kernel.org/lkml/CAHk-=whyWUdJDeOBN1hRWYSkQkvzYiQ5RbSW5rJjExgnbSNX9Q@mail.gmail.com/).

We did a minimal fix in torvalds/linux@1619b69edce1, but we should clean it up properly to avoid any issues in future.

It may be as simple as rebasing Linus' patch from above onto master.

**Comment by LukeAngove** [comment]
I've taken Linus' patch and done a bit of rework (e.g.: tidy up the Clang parameters). Is there a preference for trying to keep the resulting compile commands the same as they are presently or removing all the parameters that don't apply to building the assembly files? Essentially, should I remove flags that only apply to C code from the common vars?

**Comment by mpe** [comment]
Yes. The end result should be that we only pass flags to the assembler that the assembler actually accepts.

I think Linus' patch pretty much did that, but it would be worth going through each flag and checking whether the assembler accepts it (by looking at `man as`, and/or invoking the assembler with that flag).

**Comment by mpe** [comment]
This has bitten again, see ClangBuiltLinux/linux#1839

**Comment by npiggin** [comment]
Linus's patch seems like a reasonable approach. I think a few things could be tidied a bit while we're there though (e.g., split CPPFLAGS out rather than shoving everything in BOOTCOREFLAGS)

**Comment by LukeAngove** [comment]
If you guys are okay with me taking up to a week, I'd still like to take a shot at this; I've had a patch ready for ages, just struggled getting the simulator set up, and work taking all my time. Of course, if it's urgent or better to just get it patched, feel free to just fix it. I'll newbie another issue.

**Comment by npiggin** [comment]
Oh I've just done some patches. I didn't realise you were working on it.

You're using QEMU for the simulator? Or IBM's "Functional Simulator" systemsim? Can try to help with any issues you still have with those.

Are you interested in build system specifically or any powerpc stuff? There are a bunch of issues in medium that are non-trivial to implement, but they don't have complicated dependencies on other kernel code that makes things difficult if you're new to Linux. For example https://github.com/linuxppc/issues/issues/372, possibly https://github.com/linuxppc/issues/issues/162. There are a few build system specific ones too, e.g., https://github.com/linuxppc/issues/issues/212.

**Comment by LukeAngove** [comment]
All good; I took months to apply a simply makefile change, with essentially all the work already done in a patch. The main issues I was having were with the IBM simulator; Qemu wasn't too hard to get up and running. Also trying to set up to test both the kernel in skiboot and the main system was confusing to figure out.  I don't all that was needed for this change specifically, but getting it working in general seems important if I'm looking to contribute more.

PowerPC is more my target, though honestly, I'm just trying to get into kernel dev in general at this stage; get a patch in, learn the processes, etc. I'll look into the issues you've linked, thanks!

**Comment by npiggin** [comment]
Okay. QEMU is actually pretty good for testing PowerNV and pseries kernels, and it's got decent support for several 32-bit and BookE platforms, and of course is widely used by other Linux archs and other open source projects so I would recommend using that to start with.

Nothing wrong with systemsim, it can sometimes implement instructions that QEMU does not for example, so if something crashes or behaves strangely in QEMU it can be worth checking in systemsim. It's just a niche tool so you'll get more value to start with by learning QEMU.

There's a couple of config issues as well, e.g., https://github.com/linuxppc/issues/issues/27 might be time to revisit those since mpe has done some config rework in the powerpc next branch (some of those issues might be covered by that rework so just check that if you look at them).

**Comment by mpe** [comment]
Series from @npiggin https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=358262

**Comment by mpe** [comment]
Merged in torvalds/linux@8bce81dbce4f3563fffca48ebfce208b1112ab09 - thanks @npiggin :pineapple:
