### ISSUE TITLE
Clean-up/split asm-prototypes.h

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#392]
We originally added `asm-prototypes.h` in torvalds/linux@42f5b4cacd78, it's purpose was `for prototypes of C functions that are only called from asm`, in order to fix sparse warnings about missing prototypes.

A few months later Nick added a different use case in torvalds/linux@4efca4ed05cbdfd13, ie. for `C prototypes for exported asm functions`. This is basically the inverse of our original usage.

Since then we've added various prototypes to `asm-prototypes.h` for both reasons, meaning we now need to spend a bit of effort to unstitch it all.

Originally [noticed](https://lore.kernel.org/linuxppc-dev/b50b9bdd-b731-44ed-435b-e3e4b179a89a@csgroup.eu/) by Christophe.

**Comment by chleroy** [comment]
Series at 

Problem with prom_init() prototype, I wanted to move it to asm/prom.h but it conflicts with function prom_init() in drivers/gpu/drm/nouveau/nvkm/subdev/bios/shadowrom.c , so for the moment I leave it in asm/asm-prototypes.h

In the meantime, I'm preparing a big cleanup around asm/prom.h

**Comment by chleroy** [comment]
Patch submitted to remove prom_init() from the nouveau driver:

https://lore.kernel.org/linux-kernel/2d97ae92b9c06214be0e088a72cf303eb591bf01.1646414295.git.christophe.leroy@csgroup.eu/T/#u

**Comment by mpe** [comment]
Fixed except for `prom_init()` in torvalds/linux@76222808fc25.

v2 of the nouveau patch was apparently accepted for drm-misc-next, but seems to have vanished:
https://lore.kernel.org/linux-kernel/f6e72c6e6d9ae9019ad675081493372f745cbbf5.camel@redhat.com/

**Comment by mpe** [comment]
Nouveau patch is in linux-next and will appear in v5.20 as torvalds/linux@6aed665f9d8368ae1e962f44339150884bb47f5b.

**Comment by chleroy** [comment]
In parallele, the following series clears the conflict with nouveau:

<https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=304385&state=*>

**Comment by mpe** [comment]
Last series merged as torvalds/linux@7dc3ba0a071892ea212f90f63738fd9f81b1f638

Final piece: http://patchwork.ozlabs.org/project/linuxppc-dev/patch/20220818050659.187181-1-mpe@ellerman.id.au/

**Comment by mpe** [comment]
Final piece merged as torvalds/linux@eb316ae798b36b2.
