### ISSUE TITLE
Feature: papr_scm: Add support for smart inject

### ISSUE THREAD

**Issue by vaibhav92** [linuxppc/issues#393]
The patch would add support for injecting smart events in papr_scm exposed nvdimms.

https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20220124202204.1488346-1-vaibhav@linux.ibm.com/

**Comment by mpe** [comment]
Merged as torvalds/linux@bbbca72352bb9484bc057c91a408332b35ee8f4c
