### ISSUE TITLE
Implement support of prefixed instructions in KVM

### ISSUE THREAD

**Issue by chleroy** [linuxppc/issues#397]
RFC from @iamjpn at https://patchwork.ozlabs.org/project/linuxppc-dev/list/?state=*&series=196573

**Comment by npiggin** [comment]
This came up again, it needs to be added. @iamjpn is taking another look.

**Comment by npiggin** [comment]
@paulusmack has a series that looks good

https://lists.ozlabs.org/pipermail/linuxppc-dev/2023-March/255663.html

**Comment by npiggin** [comment]
This is upstream now, can be closed.

**Comment by mpe** [comment]
Merged in torvalds/linux@a3800ef9c48c
