### ISSUE TITLE
Don't set ppc_md.get_irq() at buildtime and use static call

### ISSUE THREAD

**Issue by chleroy** [linuxppc/issues#398]
Most of the time, `ppc_md.get_irq()` needs runtime initialised objects to work properly. Therefore it shouldn't be set before those objects are successfully initialised.

See discussion at https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20220223070223.26845-1-hbh25y@gmail.com/

And as `ppc_md.get_irq()` is used in a quite hot path, it would be good to use static calls instead of the `ppc_md` structure for it.

**Comment by chleroy** [comment]
See patch https://patchwork.ozlabs.org/project/linuxppc-dev/patch/afb92085f930651d8b1063e4d4bf0396c80ebc7d.1647002274.git.christophe.leroy@csgroup.eu/

**Comment by ruscur** [comment]
Merged for 5.19 as torvalds/linux@e59596a2d6a75ea3deb60698b95942aaf03681f5
