### ISSUE TITLE
ppc32: Implement CLOCK_MONOTONIC_COARSE etc in the vdso

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#41]
See:

> The other day, I was curious how the vdso was implemented on ppc, and I
> noted that neither ppc32 or ppc64 handle the _COARSE versions of
> CLOCK_{REALTIME,MONOTONIC} in the vdso, so they fall back to an actual
> syscall. And sure enough, measuring CLOCK_MONOTONIC
> vs. CLOCK_MONOTONIC_COARSE shows that the latter has three times as much
> overhead as the former.

https://lists.ozlabs.org/pipermail/linuxppc-dev/2016-April/141552.html

**Comment by chleroy** [comment]
Proposed patch for vdso32 at https://patchwork.ozlabs.org/patch/1148176/

**Comment by chleroy** [comment]
Merged in v5.6 for VDSO32 (https://github.com/linuxppc/linux/commit/654abc69ef2e69712e6d4e8a6cb9292b97a4aa39)
Merged in v4.16 for VDSO64 (https://github.com/linuxppc/linux/commit/5c929885f1bb4b77f85b1769c49405a0e0f154a1)
