### ISSUE TITLE
binutils warning: LOAD segment with RWX permissions

### ISSUE THREAD

**Issue by shenki** [linuxppc/issues#417]
Newer binutils emit a warning when linking the kernel:
```
powerpc64le-linux-gnu-ld: warning: .tmp_vmlinux.kallsyms1 has a LOAD segment with RWX permissions
powerpc64le-linux-gnu-ld: warning: .tmp_vmlinux.kallsyms2 has a LOAD segment with RWX permissions
powerpc64le-linux-gnu-ld: warning: vmlinux has a LOAD segment with RWX permissions
powerpc64le-linux-gnu-ld: warning: arch/powerpc/boot/zImage.pseries has a LOAD segment with RWX permissions
powerpc64le-linux-gnu-ld: warning: arch/powerpc/boot/zImage.epapr has a LOAD segment with RWX permissions
```

From https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=ba951afb99912da01a6e8434126b8fac7aa75107

An option would be to set `--no-warn-rwx-segments` on the linker command line.

Other arches will hit this too, including x86:
```
x86_64-linux-gnu-ld: warning: arch/x86/boot/setup.elf has a LOAD segment with RWX permissions
```

**Comment by mpe** [comment]
I *think* we just want to turn the warning off.

The vmlinux has a single LOAD segment covering text and data, so it needs to be RWX. The kernel is also generally not loaded by a proper ELF loader, it's just splatted into memory with the MMU off, so the permissions don't really have any meaning anyway.

**Comment by mpe** [comment]
Which is what Xen are doing:
https://lore.kernel.org/xen-devel/b3e9750f-4dd6-342e-b550-21bec8da49e6@suse.com/

**Comment by mpe** [comment]
This should be fixed for vmlinux etc. in 6.0 with torvalds/linux@0d362be5b142.

We probably need to make a similar change to `arch/powerpc/boot/Makefile` so I'll leave this open for now.

**Comment by shenki** [comment]
x86 boot and vdso: https://github.com/torvalds/linux/commit/ffcf9c5700e49c0aee42dcba9a12ba21338e8136

**Comment by ruscur** [comment]
Fixed by https://github.com/ruscur/linux/commit/579aee9fc594af94c242068c011b0233563d4bbf
