### ISSUE TITLE
Kernel stack randomisation syscall cost

### ISSUE THREAD

**Issue by npiggin** [linuxppc/issues#419]
Syscall kernel stack randomisation was recently implemented

https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/commit/?id=f4a0318f278d98d9492916722e85f258c2221f88

mftb() is allegedly used for performance, but it can be an expensive operation on POWER CPUs. x86 and s390 seem to use clocks for this. arm64 uses get_random_int.

Benchmark and test which is faster, or think up an even better 3rd approach.

**Comment by npiggin** [comment]
One thing to note is that VIRT_CPU_ACCOUNTING uses mftb() on syscall / interrupt entry to timestamp it. Sharing this value for both entry timestamp and accounting may be the best way to go when that option is enabled, but it would require some surgery to the accounting code probably. When the option is disabled, mftb() may not be the fastest.

One thing to consider with mftb is that some bits may not be so randomly distributed as others, particularly lowest few bits on some implementations can saturate between TOD pulses I think. If we do stick with mftb we might want to look at distributions and see whether we are using the right bits.

**Comment by mpe** [comment]
I did confirm that by default the `mftb()` is out of line, behind the jump label, so there should be no overhead unless the feature is actually turned on.

**Comment by chleroy** [comment]
If I understood correctly, the call to `mftb()` is done _after_ the call in order to increase the randomness. If the call to `mftb()` is done before the call, then it may be easier to guess from userspace what value `mftb()` will return.
So maybe the call to `choose_random_kstack_offset()` should be moved to `syscall_exit_prepare()` and they use the value `acct->starttime_user` stored by `account_cpu_user_exit()`

**Comment by chleroy** [comment]
That's explained in `include/linux/randomize_kstack.h` :

```
/**
 * choose_random_kstack_offset - Choose the random offset for the next
 *				 add_random_kstack_offset()
 *
 * This should only be used during syscall exit when interrupts and
 * preempt are disabled. This position in the syscall flow is done to
 * frustrate attacks from userspace attempting to learn the next offset:
 * - Maximize the timing uncertainty visible from userspace: if the
 *   offset is chosen at syscall entry, userspace has much more control
 *   over the timing between choosing offsets. "How long will we be in
 *   kernel mode?" tends to be more difficult to predict than "how long
 *   will we be in user mode?"
 * - Reduce the lifetime of the new offset sitting in memory during
 *   kernel mode execution. Exposure of "thread-local" memory content
 *   (e.g. current, percpu, etc) tends to be easier than arbitrary
 *   location memory exposure.
 */

```

**Comment by mpe** [comment]
Quick benchmark results using `null_syscall` on a Power10.

Description     | cycles | %
----------------|--------|------
compiled out    | 283.79 | -
disabled        | 284.31 | 100%
mftb            | 300.99 | 106%
get_random_init | 340.65 | 120%

The `get_random_int()` version is a bit silly as it generates 32-bits of randomness even though we know only 7 bits will be used, but doing anything more complicated starts opening up various attack possibilities.

**Comment by mpe** [comment]
I hacked up the `stack-entropy.sh` test to get 100,000 offsets and look at the distribution.

Both `mftb()` and `get_random_int()` looks more or less uniform, except that an offset of zero is quite rare (which I think is expected becuase we xor subsequent values together). So at least on Power10 it doesn't look like `mftb()` shows any bias.

**Comment by npiggin** [comment]
Nice. Well that's better than I thought on both counts.

**Comment by npiggin** [comment]
This can be closed then, mftb() looks like a reasonable choice.
