### ISSUE TITLE
Use -fpatchable-function-entry to get -mnop-mcount functionality

### ISSUE THREAD

**Issue by npiggin** [linuxppc/issues#447]
-fpatchable-function-entry will insert a number of nops at the local function entry point. This can be used to give us 2 nops at each local entry point. Then ftrace_need_init_nop() can return false (like CONFIG_HAVE_NOP_MCOUNT) without having to patch them out with objtool or implement -mnop-mcount in gcc and clang (which is unlikely to happen now that this option exists).

This could supersede -pg -mprofile-kernel options entirely. The patchable_function_entry attribute could be used for notrace functions.

Earlier compilers generate buggy code for ELFv2 with functions with global entry points, building the following code with -fpatchable-function-entry=1 should be a test for whether the option can be used
```
void bar(void);
void foo(void)
{
        bar();
}
```
This would allow us some future flexibility with the ABI as well, rather than being bound to mprofile-kernel's 2 nops. A single nop could be used with return address being found by reading and decoding the branch at LR-4, or 3 nops could be used to solve the link stack predictor problem (e.g., by returning with blr, with the original LR in r0, the 3rd nop would put that back into LR).

**Comment by rnav** [comment]
We will need a way to handle large kernels. The current approach (https://github.com/linuxppc/linux/commit/67361cf80712867329a9cd3ff0e3171545cfc867) only addresses this partially by re-writing long branches to `_mcount` to instead go to `ftrace_regs_caller`. We don't handle plt stubs today.

This also ties into #386 

With respect to the link stack predictor, a related thought is if we can have the compiler skip generation of a subsequent `mflr r0` in the function prolog. This means we don't have to nop-out `mflr r0` in the `-mprofile-kernel` sequence (or with `-fpatchable-function-entry`). `ftrace_caller` can then use `blr` and leave the return address in `r0`.

**Comment by npiggin** [comment]
Ah, that puts a spanner in the works.

Yes that's an interesting point about avoiding the second mflr. That does mean functions that or parths though functions that can avoid setting up a stack frame would always have to execute the mflr even when ftrace was not active, unless you had compiler give you metadata to find and patch out the normal mflr instructions when you enable ftrace, but that's starting to get very complicated.

**Comment by chleroy** [comment]
I'm having hard time seeing how we can handle large kernels with -fpatchable-function-entry

With -pg, gcc generates calls to mcount, and ld adds trampolines when mcount is outside of bl range, and at runtime those trampolines get modified to go to ftrace functions instead.

But with -fpatchable-function-entry there is nothing to tell ld to generate trampolines. And once vmlinux is linked it is too late to add trampolines in the middle of the kernel so it can't be done at runtime.

**Comment by npiggin** [comment]
I'm not sure how you can support that because if you can't reach the end of .text from the start of .text then the stubs there don't help you. Linker stubs that are generated when it sees the mcount branch means your instruction always has a stub within direct branch range.

**Comment by chleroy** [comment]
If we can make sure that ftrace functions are located in first half of .text then no trampoline is needed to reach them from anywhere in that first halt. Then the trampoline located at the end of .end is only needed for functions in the second half of .text and is reachable. (For a max 64Mbytes kernel of course).

**Comment by rnav** [comment]
In practice, `ftrace_caller` almost always ends up being within the first 1MB of .text. It might be better to make that explicit though.

**Comment by mpe** [comment]
Implemented in torvalds/linux@0f71dcfb4aef6043da6cc509e7a7f6a3ae87c12d
