### ISSUE TITLE
Reduce static sizing data structures with NR_CPUS 

### ISSUE THREAD

**Issue by npiggin** [linuxppc/issues#452]
In some cases it's fine to use NR_CPUs to size things, e.g., in early boot before per-cpu subsystem is up, if they can be marked with initdata then there is not much point to complicate code. In other cases they should be avoided with dynamic allocations, percpu data, putting things in paca if necessary, etc.

**Comment by chleroy** [comment]
Similar to https://github.com/linuxppc/issues/issues/134 ?

**Comment by npiggin** [comment]
Oh you're right it is, I got that mixed up with NR_IRQS one. Sorry for the noise.
