### ISSUE TITLE
VM_WARN_ON in __pte_flags_need_flush (false positive)

### ISSUE THREAD

**Issue by npiggin** [linuxppc/issues#458]
VM_WARN_ON_ONCE(oldval & _PAGE_PRIVILEGED);
        VM_WARN_ON_ONCE(newval & _PAGE_PRIVILEGED);

These can be hit because PAGE_NONE ptes get the _PAGE_PRIVILEGED bit set. Not because the PTE somehow becomes a kernel mapping when mmap()ped with PROT_NONE, it is just a quirk of our PTE encoding.

These warnings should permit PAGE_NONE encodings.

**Comment by BenjaminGrayNp1** [comment]
Minimal reproducible example:

```c
#include <sys/mman.h>
#include <unistd.h>

int main(int argc, char **argv)
{
	char *buf = mmap(NULL, getpagesize(), PROT_WRITE, MAP_SHARED | MAP_ANONYMOUS, -1, 0);
	buf[0] = '1';
	mprotect(buf, getpagesize(), PROT_NONE);
	return 0;
}
```

**Comment by BenjaminGrayNp1** [comment]
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20230302225947.81083-1-bgray@linux.ibm.com/

**Comment by BenjaminGrayNp1** [comment]
Merged in https://patchwork.ozlabs.org/project/linuxppc-dev/patch/87lejabnq1.fsf@mpe.ellerman.id.au/
