### ISSUE TITLE
Add dynamic DEXCR support

### ISSUE THREAD

**Issue by chleroy** [linuxppc/issues#476]
See RFC at https://patchwork.ozlabs.org/project/linuxppc-dev/cover/20231009055406.142940-1-bgray@linux.ibm.com/ from @BenjaminGrayNp1

**Comment by ajdlinux** [comment]
Final version of @BenjaminGrayNp1's series at https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=403371&state=* has been merged as torvalds/linux@9248edf31ab28723fb00900ecb8bacdb05eeefff
