### ISSUE TITLE
Could GCC move __patch_instruction() flushing around ?

### ISSUE THREAD

**Issue by chleroy** [linuxppc/issues#480]
Long time ago @ozbenh proposed a patch to prevent GCC from moving the flushing around in __patch_instruction(), see https://patchwork.ozlabs.org/project/linuxppc-dev/patch/48284701fe497bb4f5bede5c55bbce9d70309562.camel@kernel.crashing.org/

Is this change needed, and are there any other parts of the kernel that require such attention ?

**Comment by mpe** [comment]
The result of the patch discussion was that `asm` blocks with no outputs are implicitly volatile.

That is documented in the GCC manual in section [6.48.2.1 of v14.2.0](https://gcc.gnu.org/onlinedocs/gcc-14.2.0/gcc/Extended-Asm.html#Volatile-1), which says:

> asm statements that have no output operands and asm goto statements, are implicitly volatile.

So I think the code is OK as-is.

I would take a patch to change it to `asm volatile`, or add a comment, but it would need a changelog that is accurate, which the patch above is not.
