### ISSUE TITLE
Enable NO_HZ_FULL

### ISSUE THREAD

**Issue by mikey** [linuxppc/issues#69]
Enable NO_HZ_FULL on powerpc.  Looks like we need HAVE_CONTEXT_TRACKING (which is enabled on pseries but not powernv?!?) and HAVE_VIRT_CPU_ACCOUNTING_GEN.

With this I can boot and run bare metal, but we need to check we've actually met these new config option requirements.

**Comment by npiggin** [comment]
CORAL have been testing this with good results, and they're asking it to be turned on for RHEL, so we might want to enable it in defconfigs now.

**Comment by mpe** [comment]
Yeah sounds good.

**Comment by npiggin** [comment]
This can be closed. I opened a new one for PPC32.
