### ISSUE TITLE
Implement optimised refcount_t ?

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#87]
We may want to implement optimised versions of the `refcount_t` routines.

See commit linuxppc/linux@f405df5de317.

And https://lkml.org/lkml/2017/2/20/594:

> be marked __weak, so that architectures like ARM/PPC can decide
to do their own improved implementations.

**Comment by chleroy** [comment]
A use of refcount_t was proposed and declined due to lack of optimised version : https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20190808071808.6531-1-hslester96@gmail.com/

To be reconsidered once we have implemented it.

**Comment by chleroy** [comment]
The possibility offered in the past to architectures to implement an optimised version of refcount_t was removed by commit https://github.com/linuxppc/linux/commit/fb041bb7c0a918b95c6889fc965cdc4a75b4c0ca
