### ISSUE TITLE
Implement save_stack_trace_tsk_reliable()

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#90]
The latest changes to live patching require an arch to implement `save_stack_trace_tsk_reliable()`.

When a function `f` is live patched, `save_stack_trace_tsk_reliable()` is called for a task to determine if that task is "using" `f`. Using means either running currently in `f`, or may ever return through `f`. To determine that, we need to walk the stack, and only return the stack trace if we're confident we can guarantee the validity of the stack trace.

See: https://patchwork.ozlabs.org/patch/727652/

**Comment by chleroy** [comment]
Apparently this was implemented, see linuxppc/linux@df78d3f6148092d33a9a24c7a9cfac3d0220b484

**Comment by mpe** [comment]
Yes, thanks.

And also linuxppc/linux@eddd0b332304.
